In [1]:
# Generic Database explorer

In [29]:
from dbUtils import tablesDescription, lastHistory

In [4]:
tablesDescription('macrodata/_data/macroDatabase.db')

In [31]:
lastHistory('macrodata/_data/macroDatabase.db',
            'monthly_history', 24)

,aluminum_fut,AUDUSD=X,BBEU,BRL=X,brent_oil_fut,CAD=X,coccoa_fut,CEMB,wti_oil_fut,corp,...,cny_oil_output,cny_ng_output,cny_ip,jpy_cpi,uk_halifax_housing,us_10y_real_rate2,us_20y_real_rate,us_30y_real_rate,us_5y_real_rate,us_7y_real_rate
index,,,,,,,,,,,,,,,,,,,,,
2022-01-31,3417.00,0.718649,52.212791,5.1594,100.989998,1.27552,2491.0,44.869770,95.720001,104.395065,...,1673.7,186.2,5.0,100.3,0.003,-0.65,-0.29,-0.12,-1.20,-0.90
2022-02-28,3500.00,0.750300,52.241352,4.7697,107.910004,1.24823,2650.0,44.485531,100.279999,101.486923,...,1673.7,186.2,5.0,100.7,0.005,-0.79,-0.34,-0.11,-1.40,-1.07
2022-03-31,3049.75,0.710884,49.014713,4.9703,109.339996,1.27464,2597.0,43.164738,104.690002,96.079536,...,1771.3,196.8,5.0,101.1,0.014,-0.52,-0.20,-0.03,-0.92,-0.71
2022-04-30,NaN,0.719520,50.198547,4.7524,NaN,1.26552,NaN,43.132015,NaN,97.212250,...,1699.6,177.0,-2.9,101.5,0.011,0.01,0.27,0.40,-0.38,-0.17
2022-05-31,2401.50,0.688047,43.992950,5.1809,114.809998,1.28833,2291.0,41.468952,105.760002,94.565338,...,1756.7,177.0,0.7,101.8,0.010,0.21,0.51,0.67,-0.15,0.03
2022-06-30,2463.50,0.700084,47.737633,5.1708,110.010002,1.27777,2323.0,42.188839,98.620003,97.902374,...,1719.5,173.0,3.9,101.8,0.018,0.65,0.82,0.91,0.43,0.54
2022-07-31,2341.75,0.685740,44.212845,5.1219,96.489998,1.30895,2427.0,42.314476,89.550003,94.508789,...,1712.6,170.6,3.8,102.3,-0.001,0.14,0.47,0.71,-0.03,0.04
2022-08-31,2157.25,0.651300,39.799461,5.3962,87.959999,1.36745,2354.0,40.373920,79.489998,90.161423,...,1694.1,169.8,4.2,102.7,0.004,0.67,0.82,0.96,0.72,0.69
2022-09-30,2229.00,0.640131,43.415291,5.2885,94.830002,1.36081,2335.0,39.358891,86.529999,89.188301,...,1680.9,164.1,6.3,103.1,-0.001,1.68,1.68,1.74,1.92,1.77
2022-10-31,2460.50,0.668409,49.307510,5.2682,85.430000,1.35836,2451.0,42.180771,80.550003,93.856010,...,NaN,NaN,NaN,103.7,-0.004,1.58,1.64,1.69,1.60,1.59
2022-11-30,2410.25,0.680700,48.272392,5.2829,85.910004,1.35660,2600.0,42.247986,80.260002,92.704544,...,NaN,NaN,NaN,NaN,-0.023,1.34,1.40,1.46,1.41,1.37
2022-12-31,NaN,0.705810,53.029999,5.1149,NaN,1.33838,NaN,44.139004,NaN,97.080002,...,NaN,NaN,NaN,NaN,NaN,1.58,1.62,1.67,1.66,1.61
2023-01-31,2518.50,0.688780,52.889999,5.1457,83.690002,1.34410,2581.0,43.780228,77.139999,95.870003,...,NaN,NaN,NaN,NaN,NaN,1.28,1.36,1.43,1.36,1.31
2023-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-11-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
from datetime import date
import macrodata as md

In [54]:
md.Explorer.tickers

True

In [9]:
countries = ['Brazil', 'US']
asset_classes = ['Inflation']

In [10]:
items = md.Explorer.countryAssetList(countries, asset_classes)

In [11]:
items

{'Brazil': {'Inflation': []},
 'US': {'Inflation': ['us_cpi',
   'us_cpi_core',
   'us_cpi_food',
   'us_cpi_energy',
   'us_cpi_gasoline',
   'us_cpi_medicare',
   'us_cpi_shelter',
   'us_cpi_rent_sa']}}

In [8]:
items = md.Explorer.sourceList(['treasury'])

In [9]:
items['treasury']

['us_5y_real_rate',
 'us_7y_real_rate',
 'us_10y_real_rate2',
 'us_20y_real_rate',
 'us_30y_real_rate']

In [11]:
tickers = ['BBEU', 'IXP']
start_dt = date(2022, 1, 1)
end_dt = date(2023, 2, 1)

In [ ]:
('eu_ind_conf', -22.1),
  ('eu_ind_inventories', 19.2),
  ('de_ind_conf', -19.9),
  ('uk_ind_conf', -53.1),

In [12]:
md.Explorer.listHistory(items['treasury'], start_dt, end_dt)

,us_5y_real_rate,us_7y_real_rate,us_10y_real_rate2,us_20y_real_rate,us_30y_real_rate
index,,,,,
2022-01-31,-1.20,-0.90,-0.65,-0.29,-0.12
2022-02-28,-1.40,-1.07,-0.79,-0.34,-0.11
2022-03-31,-0.92,-0.71,-0.52,-0.20,-0.03
2022-04-29,-0.38,-0.17,0.01,0.27,0.40
2022-04-30,NaN,NaN,NaN,NaN,NaN
2022-05-31,-0.15,0.03,0.21,0.51,0.67
2022-06-30,0.43,0.54,0.65,0.82,0.91
2022-07-29,-0.03,0.04,0.14,0.47,0.71
2022-07-31,NaN,NaN,NaN,NaN,NaN
2022-08-31,0.72,0.69,0.67,0.82,0.96
2022-09-30,1.92,1.77,1.68,1.68,1.74
2022-10-31,1.60,1.59,1.58,1.64,1.69
2022-11-30,1.41,1.37,1.34,1.40,1.46
2022-12-30,1.66,1.61,1.58,1.62,1.67
2022-12-31,NaN,NaN,NaN,NaN,NaN
2023-01-31,1.36,1.31,1.28,1.36,1.43

## Manager

In [32]:
import macrodata as md
from datetime import date
# from macrodata.clients import *

In [2]:
md.Manager.sources

['yahoo',
 'bls',
 'fred',
 'treasury',
 'census',
 'ons',
 'ec',
 'manual',
 'can',
 'bcb',
 'inegi',
 'philly']

In [2]:
sources = [x for x in md.Manager.sources if x not in ['ons', 'philly']]

In [3]:
for source in sources :
    result = md.Manager.updateFromSource(source)
    print(result)

Retrieving data from Yahoo Finance...
[*********************100%***********************]  74 of 74 completed

1 Failed download:
- ^MOVE: No data found for this date range, symbol may be delisted
Nothing
Retrieving data from BLS - Bureau of Labour Statistics...
Success
Retrieving data from FRED - FED St Louis Economic Data...
Success
Retrieving data from Treasury data...
Nothing
Retrieving data from Census...
Success
Retrieving data from Eurostat Data...
No data for uk_ind_conf
No data for uk_ca
No data for uk_ind_prod
Nothing
Retrieving data from Manual csv File...
Success
Retrieving data from Canada Central Bank...

/Users/gcedism/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py:73: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  result = libops.scalar_compare(x.ravel(), y, op)

Success
Retrieving data from BCB...
Nothing

/Users/gcedism/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py:73: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  result = libops.scalar_compare(x.ravel(), y, op)

Success

/Users/gcedism/opt/anaconda3/lib/python3.9/site-packages/pandas/core/ops/array_ops.py:73: FutureWarning: Comparison of Timestamp with datetime.date is deprecated in order to match the standard library behavior. In a future version these will be considered non-comparable. Use 'ts == pd.Timestamp(date)' or 'ts.date() == date' instead.
  result = libops.scalar_compare(x.ravel(), y, op)

In [2]:
result = md.Manager.updateFromSource('bls')

Retrieving data from BLS - Bureau of Labour Statistics...

In [5]:
tickers = md.Manager.separateSources(['us_cpi'])

In [24]:
start_dt = date(2000, 1, 1)
end_dt = date(2023, 1, 31)
freq = 'M'

In [6]:
from datetime import datetime as dt
from datetime import timedelta as td
from pandas.tseries.offsets import CDay
end_dt = dt.now().date() - CDay(1)
start_dt = end_dt - td(days=180)
freq = 'M'

In [2]:
items = ['eu_ind_conf',
 'eu_ind_inventories',
 'eu_retail_sales',
 'eu_retail_sales_real',
 'de_ind_conf',
 'fr_ind_conf',
 'uk_ind_conf',
 'eu_ca',
 'de_ca',
 'fr_ca',
 'uk_ca',
 'eu_ind_prod',
 'de_ind_prod',
 'fr_ind_prod',
 'uk_ind_prod']

In [36]:
start_dt = date(2020,1,1)
end_dt = date(2023,2,7)
freq='M'

In [37]:
data = md.Manager.downloadFromSource('yahoo', ['aluminum_fut'], start_dt, end_dt, freq)

Retrieving data from Yahoo Finance...
[*********************100%***********************]  1 of 1 completed

In [38]:
data

2019-12-31    1741.75
2020-01-31    1684.00
2020-03-31    1491.25
2020-04-30    1532.25
2020-05-31    1617.50
2020-06-30    1693.00
2020-07-31    1777.25
2020-08-31    1778.50
2020-09-30    1830.25
2020-11-30    1990.00
2020-12-31    1982.00
2021-01-31    2182.50
2021-02-28    2215.00
2021-03-31    2413.00
2021-04-30    2519.50
2021-05-31    2548.75
2021-06-30    2624.25
2021-08-31    2903.00
2021-09-30    2758.50
2021-10-31    2591.25
2021-11-30    2752.50
2021-12-31    3078.25
2022-01-31    3417.00
2022-02-28    3500.00
2022-03-31    3049.75
2022-05-31    2401.50
2022-06-30    2463.50
2022-07-31    2341.75
2022-08-31    2157.25
2022-09-30    2229.00
2022-10-31    2460.50
2022-11-30    2410.25
2023-01-31    2518.50
Name: aluminum_fut, dtype: float64

### Manually testing

In [18]:
import sqlalchemy as sa
import sqlalchemy.orm as orm
from sqlalchemy.engine.url import URL

In [19]:
DATABASE = {
    'drivername': 'sqlite',
    'database': 'macrodata/_data/macroDatabase.db'
}
engine = sa.create_engine(URL.create(**DATABASE))
Base = orm.declarative_base()
    
class History(Base) :
    __table__ = sa.Table('monthly_history', Base.metadata, autoload_with=engine)
    
    def __repr__(self) :
        return f'History({self.index})'

class Data(Base) :
    __table__ = sa.Table('data_specs', Base.metadata, autoload_with=engine)
    
    def __repr__(self) :
        return f'Data({self.id} from {self.source})'
    
session = orm.Session(engine)

In [20]:
items = session.scalars(sa.select(History)).all()

In [80]:
items[0].eu_ind_conf

In [21]:
from datetime import timedelta as td
isRealEndOfMonth = lambda x : (x+td(days=1)).month != x.month

In [22]:
toDelete = [item for item in items if isRealEndOfMonth(item.index) == False]

In [23]:
{toDelet.index :[(col.name, toDelet.__dict__[col.name])
 for col in toDelet.__table__.columns if toDelet.__dict__[col.name] != None]
 for toDelet in toDelete}

{datetime.date(1970, 1, 30): [('index', datetime.date(1970, 1, 30)),
  ('jpy_cpi', 30.3)],
 datetime.date(1971, 1, 29): [('index', datetime.date(1971, 1, 29)),
  ('bra_reserves', 1229.0)],
 datetime.date(1971, 2, 26): [('index', datetime.date(1971, 2, 26)),
  ('bra_reserves', 1280.0)],
 datetime.date(1971, 7, 30): [('index', datetime.date(1971, 7, 30)),
  ('bra_reserves', 1458.0)],
 datetime.date(1971, 10, 29): [('index', datetime.date(1971, 10, 29)),
  ('bra_reserves', 1576.0)],
 datetime.date(1972, 4, 28): [('index', datetime.date(1972, 4, 28)),
  ('bra_reserves', 2213.0)],
 datetime.date(1972, 9, 29): [('index', datetime.date(1972, 9, 29)),
  ('bra_reserves', 3348.0)],
 datetime.date(1972, 12, 29): [('index', datetime.date(1972, 12, 29)),
  ('bra_reserves', 4183.0)],
 datetime.date(1973, 3, 30): [('index', datetime.date(1973, 3, 30)),
  ('bra_reserves', 4920.0)],
 datetime.date(1973, 6, 29): [('index', datetime.date(1973, 6, 29)),
  ('bra_reserves', 5981.0)],
 datetime.date(1973, 9, 28): [('index', datetime.date(1973, 9, 28)),
  ('bra_reserves', 6463.0)],
 datetime.date(1974, 3, 29): [('index', datetime.date(1974, 3, 29)),
  ('bra_reserves', 6536.0)],
 datetime.date(1974, 6, 28): [('index', datetime.date(1974, 6, 28)),
  ('bra_reserves', 6516.0)],
 datetime.date(1974, 8, 30): [('index', datetime.date(1974, 8, 30)),
  ('bra_reserves', 6182.0)],
 datetime.date(1974, 11, 29): [('index', datetime.date(1974, 11, 29)),
  ('bra_reserves', 5295.0)],
 datetime.date(1975, 5, 30): [('index', datetime.date(1975, 5, 30)),
  ('bra_reserves', 4193.0)],
 datetime.date(1975, 8, 29): [('index', datetime.date(1975, 8, 29)),
  ('bra_reserves', 3891.0)],
 datetime.date(1975, 11, 28): [('index', datetime.date(1975, 11, 28)),
  ('bra_reserves', 3679.0)],
 datetime.date(1976, 1, 30): [('index', datetime.date(1976, 1, 30)),
  ('bra_reserves', 3868.0)],
 datetime.date(1976, 2, 27): [('index', datetime.date(1976, 2, 27)),
  ('bra_reserves', 3673.0)],
 datetime.date(1976, 7, 30): [('index', datetime.date(1976, 7, 30)),
  ('bra_reserves', 3948.0)],
 datetime.date(1976, 10, 29): [('index', datetime.date(1976, 10, 29)),
  ('bra_reserves', 4956.0)],
 datetime.date(1977, 4, 29): [('index', datetime.date(1977, 4, 29)),
  ('bra_reserves', 5787.0)],
 datetime.date(1977, 7, 29): [('index', datetime.date(1977, 7, 29)),
  ('bra_reserves', 6147.0)],
 datetime.date(1977, 12, 30): [('index', datetime.date(1977, 12, 30)),
  ('bra_reserves', 7256.0)],
 datetime.date(1978, 4, 28): [('index', datetime.date(1978, 4, 28)),
  ('bra_reserves', 7553.0)],
 datetime.date(1978, 9, 29): [('index', datetime.date(1978, 9, 29)),
  ('bra_reserves', 10026.0)],
 datetime.date(1978, 12, 29): [('index', datetime.date(1978, 12, 29)),
  ('bra_reserves', 11895.0)],
 datetime.date(1979, 3, 30): [('index', datetime.date(1979, 3, 30)),
  ('bra_reserves', 11136.0)],
 datetime.date(1979, 6, 29): [('index', datetime.date(1979, 6, 29)),
  ('bra_reserves', 10108.0)],
 datetime.date(1979, 9, 28): [('index', datetime.date(1979, 9, 28)),
  ('bra_reserves', 9327.0)],
 datetime.date(1980, 5, 30): [('index', datetime.date(1980, 5, 30)),
  ('eu_ind_conf', -14.3),
  ('eu_ind_inventories', 12.5),
  ('de_ind_conf', -9.3),
  ('uk_ind_conf', -39.0),
  ('bra_ipca_MoM', 5.7),
  ('bra_reserves', 6688.0)],
 datetime.date(1980, 8, 29): [('index', datetime.date(1980, 8, 29)),
  ('eu_ind_conf', -22.1),
  ('eu_ind_inventories', 19.2),
  ('de_ind_conf', -19.9),
  ('uk_ind_conf', -53.1),
  ('bra_ipca_MoM', 4.95),
  ('bra_reserves', 6970.0)],
 datetime.date(1980, 11, 28): [('index', datetime.date(1980, 11, 28)),
  ('eu_ind_conf', -27.6),
  ('eu_ind_inventories', 23.6),
  ('de_ind_conf', -24.1),
  ('uk_ind_conf', -50.4),
  ('bra_ipca_MoM', 6.67),
  ('bra_reserves', 6185.0)],
 datetime.date(1981, 1, 30): [('index', datetime.date(1981, 1, 30)),
  ('eu_ind_conf', -28.3),
  ('eu_ind_inventories', 24.2),
  ('de_ind_conf', -25.8),
  ('uk_ind_conf', -40.9),
  ('bra_ipca_MoM', 6.84),
  ('bra_reserves', 6627.0)],
 datetime.date(1981, 2, 27): [('index', datetime.date(1981, 2, 27)),
  ('eu_ind_conf', -27.7),
  ('eu_ind_inventories', 24.6),
  ('de_ind_conf', -24.3),
  ('uk_ind_conf', -40.2),
  ('bra_ipca_MoM', 6.4),
  ('bra_reserves', 6584.0)],
 datetime.date(1981, 5, 29): [('index', datetime.date(1981, 5, 29)),
  ('eu_ind_conf', -29.0),
  ('eu_ind_inventories', 25.7),
  ('de_ind_conf', -24.6),
  ('uk_ind_conf', -32.8),
  ('bra_ipca_MoM', 5.56),
  ('bra_reserves', 6370.0)],
 datetime.date(1981, 10, 30): [('index', datetime.date(1981, 10, 30)),
  ('eu_ind_conf', -26.3),
  ('eu_ind_inventories', 24.8),
  ('de_ind_conf', -22.9),
  ('uk_ind_conf', -24.0),
  ('bra_ipca_MoM', 5.08),
  ('bra_reserves', 6408.0)],
 datetime.date(1982, 1, 29): [('index', datetime.date(1982, 1, 29)),
  ('eu_ind_conf', -26.6),
  ('eu_ind_inventories', 22.4),
  ('de_ind_conf', -24.8),
  ('uk_ind_conf', -25.5),
  ('bra_ipca_MoM', 6.97),
  ('bra_reserves', 7280.0)],
 datetime.date(1982, 2, 26): [('index', datetime.date(1982, 2, 26)),
  ('eu_ind_conf', -27.8),
  ('eu_ind_inventories', 24.1),
  ('de_ind_conf', -24.3),
  ('uk_ind_conf', -26.2),
  ('bra_ipca_MoM', 6.64),
  ('bra_reserves', 7080.0)],
 datetime.date(1982, 7, 30): [('index', datetime.date(1982, 7, 30)),
  ('eu_ind_conf', -31.6),
  ('eu_ind_inventories', 25.7),
  ('de_ind_conf', -29.8),
  ('uk_ind_conf', -26.1),
  ('bra_ipca_MoM', 6.36),
  ('bra_reserves', 7035.0)],
 datetime.date(1982, 10, 29): [('index', datetime.date(1982, 10, 29)),
  ('eu_ind_conf', -34.3),
  ('eu_ind_inventories', 27.7),
  ('de_ind_conf', -34.5),
  ('uk_ind_conf', -25.2),
  ('bra_ipca_MoM', 4.44),
  ('bra_reserves', 3877.0)],
 datetime.date(1983, 4, 29): [('index', datetime.date(1983, 4, 29)),
  ('eu_ind_conf', -24.5),
  ('eu_ind_inventories', 19.2),
  ('de_ind_conf', -17.8),
  ('uk_ind_conf', -11.6),
  ('bra_ipca_MoM', 6.58),
  ('bra_reserves', 3587.0)],
 datetime.date(1983, 7, 29): [('index', datetime.date(1983, 7, 29)),
  ('eu_ind_conf', -21.4),
  ('eu_ind_inventories', 18.0),
  ('de_ind_conf', -16.8),
  ('uk_ind_conf', -9.6),
  ('bra_ipca_MoM', 10.08),
  ('bra_reserves', 3822.0)],
 datetime.date(1983, 12, 30): [('index', datetime.date(1983, 12, 30)),
  ('eu_ind_conf', -12.7),
  ('eu_ind_inventories', 13.1),
  ('de_ind_conf', -7.9),
  ('uk_ind_conf', 3.0),
  ('bra_ipca_MoM', 8.68),
  ('bra_reserves', 4563.0)],
 datetime.date(1984, 3, 30): [('index', datetime.date(1984, 3, 30)),
  ('eu_ind_conf', -11.7),
  ('eu_ind_inventories', 13.2),
  ('de_ind_conf', -8.1),
  ('uk_ind_conf', 2.4),
  ('bra_ipca_MoM', 8.94),
  ('bra_reserves', 5936.0)],
 datetime.date(1984, 6, 29): [('index', datetime.date(1984, 6, 29)),
  ('eu_ind_conf', -10.9),
  ('eu_ind_inventories', 11.1),
  ('de_ind_conf', -8.9),
  ('uk_ind_conf', -0.8),
  ('bra_ipca_MoM', 10.08),
  ('bra_reserves', 7950.0)],
 datetime.date(1984, 9, 28): [('index', datetime.date(1984, 9, 28)),
  ('eu_ind_conf', -9.2),
  ('eu_ind_inventories', 11.9),
  ('de_ind_conf', -7.0),
  ('uk_ind_conf', -1.5),
  ('bra_ipca_MoM', 11.75),
  ('bra_reserves', 9639.0)],
 datetime.date(1985, 3, 29): [('index', datetime.date(1985, 3, 29)),
  ('eu_ind_conf', -8.4),
  ('eu_ind_inventories', 11.4),
  ('de_ind_conf', -5.3),
  ('fr_ind_conf', -19.1),
  ('uk_ind_conf', -0.1),
  ('bra_ipca_MoM', 10.16),
  ('bra_reserves', 11454.0)],
 datetime.date(1985, 6, 28): [('index', datetime.date(1985, 6, 28)),
  ('eu_ind_conf', -7.1),
  ('eu_ind_inventories', 11.4),
  ('de_ind_conf', -4.9),
  ('fr_ind_conf', -16.5),
  ('uk_ind_conf', 3.3),
  ('bra_ipca_MoM', 8.49),
  ('bra_reserves', 11647.0)],
 datetime.date(1985, 8, 30): [('index', datetime.date(1985, 8, 30)),
  ('eu_ind_conf', -7.0),
  ('eu_ind_inventories', 10.4),
  ('de_ind_conf', -3.9),
  ('fr_ind_conf', -16.8),
  ('uk_ind_conf', -2.6),
  ('bra_ipca_MoM', 12.05),
  ('bra_reserves', 12178.0)],
 datetime.date(1985, 11, 29): [('index', datetime.date(1985, 11, 29)),
  ('eu_ind_conf', -5.3),
  ('eu_ind_inventories', 9.5),
  ('de_ind_conf', -1.8),
  ('fr_ind_conf', -12.5),
  ('uk_ind_conf', -0.5),
  ('bra_ipca_MoM', 13.97),
  ('bra_reserves', 11862.0)],
 datetime.date(1986, 5, 30): [('index', datetime.date(1986, 5, 30)),
  ('eu_ind_conf', -6.6),
  ('eu_ind_inventories', 11.5),
  ('de_ind_conf', -5.9),
  ('fr_ind_conf', -11.4),
  ('uk_ind_conf', -7.9),
  ('bra_ipca_MoM', 1.4),
  ('bra_reserves', 10419.0)],
 datetime.date(1986, 8, 29): [('index', datetime.date(1986, 8, 29)),
  ('eu_ind_conf', -6.5),
  ('eu_ind_inventories', 9.3),
  ('de_ind_conf', -6.3),
  ('fr_ind_conf', -10.2),
  ('uk_ind_conf', -10.6),
  ('bra_ipca_MoM', 3.55),
  ('bra_reserves', 9105.0)],
 datetime.date(1986, 11, 28): [('index', datetime.date(1986, 11, 28)),
  ('eu_ind_conf', -7.8),
  ('eu_ind_inventories', 9.7),
  ('de_ind_conf', -7.8),
  ('fr_ind_conf', -12.3),
  ('uk_ind_conf', -1.1),
  ('bra_ipca_MoM', 5.45),
  ('bra_reserves', 7347.0)],
 datetime.date(1987, 1, 30): [('index', datetime.date(1987, 1, 30)),
  ('eu_ind_conf', -8.3),
  ('eu_ind_inventories', 10.5),
  ('de_ind_conf', -11.6),
  ('fr_ind_conf', -11.2),
  ('uk_ind_conf', -2.9),
  ('bra_ipca_MoM', 13.21),
  ('bra_reserves', 5380.0)],
 datetime.date(1987, 2, 27): [('index', datetime.date(1987, 2, 27)),
  ('eu_ind_conf', -9.4),
  ('eu_ind_inventories', 11.2),
  ('de_ind_conf', -13.0),
  ('fr_ind_conf', -12.7),
  ('uk_ind_conf', 6.6),
  ('bra_ipca_MoM', 12.64),
  ('bra_reserves', 4965.0)],
 datetime.date(1987, 5, 29): [('index', datetime.date(1987, 5, 29)),
  ('eu_ind_conf', -7.2),
  ('eu_ind_inventories', 7.8),
  ('de_ind_conf', -10.8),
  ('fr_ind_conf', -8.4),
  ('uk_ind_conf', 11.5),
  ('bra_ipca_MoM', 21.45),
  ('bra_reserves', 5770.0)],
 datetime.date(1987, 10, 30): [('index', datetime.date(1987, 10, 30)),
  ('eu_ind_conf', -3.7),
  ('eu_ind_inventories', 5.6),
  ('de_ind_conf', -6.7),
  ('fr_ind_conf', 0.4),
  ('uk_ind_conf', 17.7),
  ('bra_ipca_MoM', 11.22),
  ('bra_reserves', 7341.0)],
 datetime.date(1988, 1, 29): [('index', datetime.date(1988, 1, 29)),
  ('eu_ind_conf', -3.7),
  ('eu_ind_inventories', 5.3),
  ('de_ind_conf', -8.8),
  ('fr_ind_conf', -0.7),
  ('uk_ind_conf', 16.6),
  ('bra_ipca_MoM', 18.89),
  ('bra_reserves', 7422.0)],
 datetime.date(1988, 4, 29): [('index', datetime.date(1988, 4, 29)),
  ('eu_ind_conf', -1.0),
  ('eu_ind_inventories', 4.3),
  ('de_ind_conf', -3.4),
  ('fr_ind_conf', 2.8),
  ('uk_ind_conf', 13.2),
  ('bra_ipca_MoM', 19.29),
  ('bra_reserves', 7574.0)],
 datetime.date(1988, 7, 29): [('index', datetime.date(1988, 7, 29)),
  ('eu_ind_conf', 1.7),
  ('eu_ind_inventories', 3.1),
  ('de_ind_conf', -0.4),
  ('fr_ind_conf', 7.6),
  ('uk_ind_conf', 14.6),
  ('bra_ipca_MoM', 21.91),
  ('bra_reserves', 7869.0)],
 datetime.date(1988, 12, 30): [('index', datetime.date(1988, 12, 30)),
  ('eu_ind_conf', 4.7),
  ('eu_ind_inventories', 2.3),
  ('de_ind_conf', 2.3),
  ('fr_ind_conf', 11.1),
  ('uk_ind_conf', 14.4),
  ('bra_ipca_MoM', 28.7),
  ('bra_reserves', 9140.0)],
 datetime.date(1989, 4, 28): [('index', datetime.date(1989, 4, 28)),
  ('eu_ind_conf', 4.6),
  ('eu_ind_inventories', 3.0),
  ('de_ind_conf', 4.1),
  ('fr_ind_conf', 8.2),
  ('uk_ind_conf', -0.7),
  ('bra_ipca_MoM', 8.33),
  ('bra_reserves', 9775.0)],
 datetime.date(1989, 9, 29): [('index', datetime.date(1989, 9, 29)),
  ('eu_ind_conf', 4.1),
  ('eu_ind_inventories', 3.8),
  ('de_ind_conf', 5.5),
  ('fr_ind_conf', 7.3),
  ('uk_ind_conf', -6.1),
  ('bra_ipca_MoM', 37.56),
  ('bra_reserves', 9890.0)],
 datetime.date(1989, 12, 29): [('index', datetime.date(1989, 12, 29)),
  ('eu_ind_conf', 4.1),
  ('eu_ind_inventories', 4.3),
  ('de_ind_conf', 7.3),
  ('fr_ind_conf', 2.6),
  ('uk_ind_conf', -7.1),
  ('bra_ipca_MoM', 51.5),
  ('bra_reserves', 9679.0)],
 datetime.date(1990, 3, 30): [('index', datetime.date(1990, 3, 30)),
  ('eu_ind_conf', 3.5),
  ('eu_ind_inventories', 4.4),
  ('de_ind_conf', 9.2),
  ('fr_ind_conf', 0.6),
  ('uk_ind_conf', -15.7),
  ('fr_ind_prod', 91.0),
  ('bra_ipca_MoM', 82.39),
  ('bra_reserves', 7385.0)],
 datetime.date(1990, 6, 29): [('index', datetime.date(1990, 6, 29)),
  ('eu_ind_conf', 0.9),
  ('eu_ind_inventories', 6.6),
  ('de_ind_conf', 8.4),
  ('fr_ind_conf', -2.1),
  ('uk_ind_conf', -11.5),
  ('fr_ind_prod', 90.2),
  ('bra_ipca_MoM', 11.75),
  ('bra_reserves', 10173.0)],
 datetime.date(1990, 9, 28): [('index', datetime.date(1990, 9, 28)),
  ('eu_ind_conf', -0.4),
  ('eu_ind_inventories', 5.9),
  ('de_ind_conf', 13.1),
  ('fr_ind_conf', -10.8),
  ('uk_ind_conf', -21.7),
  ('fr_ind_prod', 90.5),
  ('bra_ipca_MoM', 14.41),
  ('bra_reserves', 10171.0)],
 datetime.date(1991, 3, 29): [('index', datetime.date(1991, 3, 29)),
  ('eu_ind_conf', -10.7),
  ('eu_ind_inventories', 12.7),
  ('de_ind_conf', -5.6),
  ('fr_ind_conf', -20.2),
  ('uk_ind_conf', -39.3),
  ('de_ca', -4083.0),
  ('eu_ind_prod', 77.9),
  ('de_ind_prod', 77.3),
  ('fr_ind_prod', 90.0),
  ('bra_ipca_MoM', 11.92),
  ('bra_reserves', 8663.0)],
 datetime.date(1991, 6, 28): [('index', datetime.date(1991, 6, 28)),
  ('eu_ind_conf', -11.2),
  ('eu_ind_inventories', 13.0),
  ('de_ind_conf', -7.1),
  ('fr_ind_conf', -14.9),
  ('uk_ind_conf', -34.5),
  ('de_ca', -3236.0),
  ('eu_ind_prod', 78.8),
  ('de_ind_prod', 78.6),
  ('fr_ind_prod', 90.4),
  ('bra_ipca_MoM', 11.19),
  ('bra_reserves', 10401.0)],
 datetime.date(1991, 8, 30): [('index', datetime.date(1991, 8, 30)),
  ('eu_ind_conf', -11.8),
  ('eu_ind_inventories', 13.2),
  ('de_ind_conf', -10.4),
  ('fr_ind_conf', -16.0),
  ('uk_ind_conf', -31.8),
  ('de_ca', -1713.0),
  ('eu_ind_prod', 77.3),
  ('de_ind_prod', 75.4),
  ('fr_ind_prod', 89.9),
  ('bra_ipca_MoM', 15.63),
  ('bra_reserves', 9261.0)],
 datetime.date(1991, 11, 29): [('index', datetime.date(1991, 11, 29)),
  ('eu_ind_conf', -12.6),
  ('eu_ind_inventories', 13.5),
  ('de_ind_conf', -11.9),
  ('fr_ind_conf', -16.8),
  ('uk_ind_conf', -19.7),
  ('de_ca', 59.0),
  ('eu_ind_prod', 78.6),
  ('de_ind_prod', 77.1),
  ('fr_ind_prod', 91.2),
  ('bra_ipca_MoM', 25.21),
  ('bra_reserves', 7863.0)],
 datetime.date(1992, 2, 28): [('index', datetime.date(1992, 2, 28)),
  ('eu_ind_conf', -13.1),
  ('eu_ind_inventories', 13.7),
  ('de_ind_conf', -14.7),
  ('fr_ind_conf', -13.5),
  ('uk_ind_conf', -27.0),
  ('de_ca', -1250.0),
  ('eu_ind_prod', 79.3),
  ('de_ind_prod', 79.0),
  ('fr_ind_prod', 90.0),
  ('bra_ipca_MoM', 24.32),
  ('bra_reserves', 14378.0),
  ('bra_employment', 20945638.0)],
 datetime.date(1992, 5, 29): [('index', datetime.date(1992, 5, 29)),
  ('eu_ind_conf', -15.0),
  ('eu_ind_inventories', 14.3),
  ('de_ind_conf', -17.5),
  ('fr_ind_conf', -15.0),
  ('uk_ind_conf', -15.1),
  ('de_ca', -2005.0),
  ('eu_ind_prod', 77.9),
  ('de_ind_prod', 76.2),
  ('fr_ind_prod', 90.3),
  ('bra_ipca_MoM', 24.86),
  ('bra_reserves', 20512.0),
  ('bra_employment', 20824678.0)],
 datetime.date(1992, 10, 30): [('index', datetime.date(1992, 10, 30)),
  ('eu_ind_conf', -25.1),
  ('eu_ind_inventories', 18.8),
  ('de_ind_conf', -34.0),
  ('fr_ind_conf', -25.8),
  ('uk_ind_conf', -24.6),
  ('de_ca', -508.0),
  ('eu_ind_prod', 75.6),
  ('de_ind_prod', 73.6),
  ('fr_ind_prod', 88.8),
  ('bra_ipca_MoM', 25.24),
  ('bra_reserves', 24124.0),
  ('bra_employment', 20712817.0)],
 datetime.date(1993, 1, 29): [('index', datetime.date(1993, 1, 29)),
  ('eu_ind_conf', -29.0),
  ('eu_ind_inventories', 23.0),
  ('de_ind_conf', -35.0),
  ('fr_ind_conf', -32.9),
  ('uk_ind_conf', -21.1),
  ('de_ca', -2269.0),
  ('eu_ind_prod', 74.0),
  ('de_ind_prod', 71.0),
  ('fr_ind_prod', 86.3),
  ('bra_ipca_MoM', 30.35),
  ('bra_reserves', 23313.0),
  ('bra_employment', 20430721.0)],
 datetime.date(1993, 2, 26): [('index', datetime.date(1993, 2, 26)),
  ('eu_ind_conf', -28.7),
  ('eu_ind_inventories', 21.6),
  ('de_ind_conf', -37.0),
  ('fr_ind_conf', -33.1),
  ('uk_ind_conf', -18.2),
  ('de_ca', -72.0),
  ('eu_ind_prod', 73.4),
  ('de_ind_prod', 69.9),
  ('fr_ind_prod', 86.5),
  ('bra_ipca_MoM', 24.98),
  ('bra_reserves', 22890.0),
  ('bra_employment', 20433652.0)],
 datetime.date(1993, 7, 30): [('index', datetime.date(1993, 7, 30)),
  ('eu_ind_conf', -27.9),
  ('eu_ind_inventories', 24.0),
  ('de_ind_conf', -35.5),
  ('fr_ind_conf', -36.7),
  ('uk_ind_conf', -12.5),
  ('de_ca', -3395.0),
  ('eu_ind_prod', 71.8),
  ('de_ind_prod', 67.3),
  ('fr_ind_prod', 85.9),
  ('bra_ipca_MoM', 30.72),
  ('bra_reserves', 25937.0),
  ('bra_employment', 20721119.0)],
 datetime.date(1993, 10, 29): [('index', datetime.date(1993, 10, 29)),
  ('eu_ind_conf', -22.3),
  ('eu_ind_inventories', 18.7),
  ('de_ind_conf', -29.4),
  ('fr_ind_conf', -31.7),
  ('uk_ind_conf', -9.9),
  ('de_ca', -1023.0),
  ('eu_ind_prod', 73.3),
  ('de_ind_prod', 69.8),
  ('fr_ind_prod', 86.3),
  ('bra_ipca_MoM', 33.92),
  ('bra_reserves', 29019.0),
  ('bra_employment', 20759129.0)],
 datetime.date(1994, 4, 29): [('index', datetime.date(1994, 4, 29)),
  ('eu_ind_conf', -8.8),
  ('eu_ind_inventories', 9.8),
  ('de_ind_conf', -16.5),
  ('fr_ind_conf', -8.2),
  ('uk_ind_conf', -6.6),
  ('de_ca', -1523.0),
  ('eu_ind_prod', 75.9),
  ('de_ind_prod', 71.3),
  ('fr_ind_prod', 88.6),
  ('bra_ipca_MoM', 42.68),
  ('bra_reserves', 38289.0),
  ('bra_employment', 20632405.0)],
 datetime.date(1994, 7, 29): [('index', datetime.date(1994, 7, 29)),
  ('eu_ind_conf', -3.9),
  ('eu_ind_inventories', 6.7),
  ('de_ind_conf', -12.0),
  ('fr_ind_conf', -4.1),
  ('uk_ind_conf', -1.5),
  ('de_ca', -5064.0),
  ('eu_ind_prod', 76.5),
  ('de_ind_prod', 71.0),
  ('fr_ind_prod', 89.9),
  ('bra_ipca_MoM', 6.84),
  ('bra_reserves', 43090.0),
  ('bra_m1', 7886210.0),
  ('bra_employment', 20812413.0)],
 datetime.date(1994, 12, 30): [('index', datetime.date(1994, 12, 30)),
  ('eu_ind_conf', 3.2),
  ('eu_ind_inventories', 3.7),
  ('de_ind_conf', -1.5),
  ('fr_ind_conf', 2.3),
  ('uk_ind_conf', 9.7),
  ('de_ca', -3298.0),
  ('eu_ind_prod', 79.4),
  ('de_ind_prod', 73.4),
  ('fr_ind_prod', 91.5),
  ('bra_ipca_MoM', 1.71),
  ('bra_reserves', 38806.0),
  ('bra_m1', 14335670.0),
  ('bra_employment', 20790407.0)],
 datetime.date(1995, 4, 28): [('index', datetime.date(1995, 4, 28)),
  ('eu_ind_conf', 1.0),
  ('eu_ind_inventories', 4.2),
  ('de_ind_conf', -5.9),
  ('fr_ind_conf', 0.6),
  ('uk_ind_conf', 6.3),
  ('de_ca', -1613.0),
  ('eu_ind_prod', 79.2),
  ('de_ind_prod', 72.9),
  ('fr_ind_prod', 92.5),
  ('bra_ipca_MoM', 2.43),
  ('bra_reserves', 31887.0),
  ('bra_trade_balance', -1164.4),
  ('bra_fdi', 3.6),
  ('bra_fdi2', 167.9),
  ('bra_m1', 14581134.0),
  ('bra_employment', 20966997.0)],
 datetime.date(1995, 9, 29): [('index', datetime.date(1995, 9, 29)),
  ('eu_ind_conf', -6.1),
  ('eu_ind_inventories', 10.8),
  ('de_ind_conf', -12.4),
  ('fr_ind_conf', -10.8),
  ('uk_ind_conf', -0.7),
  ('de_ca', -2502.0),
  ('eu_ind_prod', 79.5),
  ('de_ind_prod', 72.9),
  ('fr_ind_prod', 92.6),
  ('bra_ipca_MoM', 0.99),
  ('bra_reserves', 48713.0),
  ('bra_trade_balance', -230.4),
  ('bra_fdi', 155.6),
  ('bra_fdi2', 632.4),
  ('bra_m1', 14543047.0),
  ('bra_employment', 20820381.0)],
 datetime.date(1995, 12, 29): [('index', datetime.date(1995, 12, 29)),
  ('eu_ind_conf', -9.4),
  ('eu_ind_inventories', 13.5),
  ('de_ind_conf', -14.6),
  ('fr_ind_conf', -18.9),
  ('uk_ind_conf', -7.7),
  ('de_ca', 607.0),
  ('eu_ind_prod', 79.8),
  ('de_ind_prod', 71.9),
  ('fr_ind_prod', 92.9),
  ('bra_ipca_MoM', 1.56),
  ('bra_reserves', 51840.0),
  ('bra_trade_balance', -725.6),
  ('bra_fdi', 38.5),
  ('bra_fdi2', 720.0),
  ('bra_m1', 18246488.0),
  ('bra_employment', 20661068.0)],
 datetime.date(1996, 3, 29): [('index', datetime.date(1996, 3, 29)),
  ('eu_ind_conf', -14.4),
  ('eu_ind_inventories', 17.2),
  ('de_ind_conf', -22.5),
  ('fr_ind_conf', -17.8),
  ('uk_ind_conf', -7.1),
  ('de_ca', -317.0),
  ('eu_ind_prod', 78.8),
  ('de_ind_prod', 72.0),
  ('fr_ind_prod', 93.0),
  ('bra_ipca_MoM', 0.35),
  ('bra_reserves', 55753.0),
  ('bra_trade_balance', -965.3),
  ('bra_fdi', -1432.7),
  ('bra_fdi2', 594.2),
  ('bra_m1', 15699182.0),
  ('bra_employment', 20535556.0)],
 datetime.date(1996, 6, 28): [('index', datetime.date(1996, 6, 28)),
  ('eu_ind_conf', -14.6),
  ('eu_ind_inventories', 16.9),

In [24]:
[x.index for x in toDelete]

[datetime.date(1970, 1, 30),
 datetime.date(1971, 1, 29),
 datetime.date(1971, 2, 26),
 datetime.date(1971, 7, 30),
 datetime.date(1971, 10, 29),
 datetime.date(1972, 4, 28),
 datetime.date(1972, 9, 29),
 datetime.date(1972, 12, 29),
 datetime.date(1973, 3, 30),
 datetime.date(1973, 6, 29),
 datetime.date(1973, 9, 28),
 datetime.date(1974, 3, 29),
 datetime.date(1974, 6, 28),
 datetime.date(1974, 8, 30),
 datetime.date(1974, 11, 29),
 datetime.date(1975, 5, 30),
 datetime.date(1975, 8, 29),
 datetime.date(1975, 11, 28),
 datetime.date(1976, 1, 30),
 datetime.date(1976, 2, 27),
 datetime.date(1976, 7, 30),
 datetime.date(1976, 10, 29),
 datetime.date(1977, 4, 29),
 datetime.date(1977, 7, 29),
 datetime.date(1977, 12, 30),
 datetime.date(1978, 4, 28),
 datetime.date(1978, 9, 29),
 datetime.date(1978, 12, 29),
 datetime.date(1979, 3, 30),
 datetime.date(1979, 6, 29),
 datetime.date(1979, 9, 28),
 datetime.date(1980, 5, 30),
 datetime.date(1980, 8, 29),
 datetime.date(1980, 11, 28),
 datetime.date(1981, 1, 30),
 datetime.date(1981, 2, 27),
 datetime.date(1981, 5, 29),
 datetime.date(1981, 10, 30),
 datetime.date(1982, 1, 29),
 datetime.date(1982, 2, 26),
 datetime.date(1982, 7, 30),
 datetime.date(1982, 10, 29),
 datetime.date(1983, 4, 29),
 datetime.date(1983, 7, 29),
 datetime.date(1983, 12, 30),
 datetime.date(1984, 3, 30),
 datetime.date(1984, 6, 29),
 datetime.date(1984, 9, 28),
 datetime.date(1985, 3, 29),
 datetime.date(1985, 6, 28),
 datetime.date(1985, 8, 30),
 datetime.date(1985, 11, 29),
 datetime.date(1986, 5, 30),
 datetime.date(1986, 8, 29),
 datetime.date(1986, 11, 28),
 datetime.date(1987, 1, 30),
 datetime.date(1987, 2, 27),
 datetime.date(1987, 5, 29),
 datetime.date(1987, 10, 30),
 datetime.date(1988, 1, 29),
 datetime.date(1988, 4, 29),
 datetime.date(1988, 7, 29),
 datetime.date(1988, 12, 30),
 datetime.date(1989, 4, 28),
 datetime.date(1989, 9, 29),
 datetime.date(1989, 12, 29),
 datetime.date(1990, 3, 30),
 datetime.date(1990, 6, 29),
 datetime.date(1990, 9, 28),
 datetime.date(1991, 3, 29),
 datetime.date(1991, 6, 28),
 datetime.date(1991, 8, 30),
 datetime.date(1991, 11, 29),
 datetime.date(1992, 2, 28),
 datetime.date(1992, 5, 29),
 datetime.date(1992, 10, 30),
 datetime.date(1993, 1, 29),
 datetime.date(1993, 2, 26),
 datetime.date(1993, 7, 30),
 datetime.date(1993, 10, 29),
 datetime.date(1994, 4, 29),
 datetime.date(1994, 7, 29),
 datetime.date(1994, 12, 30),
 datetime.date(1995, 4, 28),
 datetime.date(1995, 9, 29),
 datetime.date(1995, 12, 29),
 datetime.date(1996, 3, 29),
 datetime.date(1996, 6, 28),
 datetime.date(1996, 8, 30),
 datetime.date(1996, 11, 29),
 datetime.date(1997, 5, 30),
 datetime.date(1997, 8, 29),
 datetime.date(1997, 11, 28),
 datetime.date(1998, 1, 30),
 datetime.date(1998, 2, 27),
 datetime.date(1998, 5, 29),
 datetime.date(1998, 10, 30),
 datetime.date(1999, 1, 29),
 datetime.date(1999, 2, 26),
 datetime.date(1999, 7, 30),
 datetime.date(1999, 10, 29),
 datetime.date(2000, 4, 28),
 datetime.date(2000, 9, 29),
 datetime.date(2000, 12, 29),
 datetime.date(2001, 3, 30),
 datetime.date(2001, 6, 29),
 datetime.date(2001, 9, 28),
 datetime.date(2002, 3, 29),
 datetime.date(2002, 6, 28),
 datetime.date(2002, 8, 30),
 datetime.date(2002, 11, 29),
 datetime.date(2003, 5, 30),
 datetime.date(2003, 8, 29),
 datetime.date(2003, 11, 28),
 datetime.date(2004, 1, 30),
 datetime.date(2004, 2, 27),
 datetime.date(2004, 7, 30),
 datetime.date(2004, 10, 29),
 datetime.date(2005, 4, 29),
 datetime.date(2005, 7, 29),
 datetime.date(2005, 12, 30),
 datetime.date(2006, 4, 28),
 datetime.date(2006, 9, 29),
 datetime.date(2006, 12, 29),
 datetime.date(2007, 3, 30),
 datetime.date(2007, 6, 29),
 datetime.date(2007, 9, 28),
 datetime.date(2008, 5, 30),
 datetime.date(2008, 8, 29),
 datetime.date(2008, 11, 28),
 datetime.date(2009, 1, 30),
 datetime.date(2009, 2, 27),
 datetime.date(2009, 5, 29),
 datetime.date(2009, 10, 30),
 datetime.date(2010, 1, 29),
 datetime.date(2010, 2, 26),
 datetime.date(2010, 7, 30),
 datetime.date(2010, 10, 29),
 datetime.date(2011, 4, 29),
 datetime.date(2011, 7, 29),
 datetime.date(2011, 12, 30),
 datetime.date(2012, 3, 30),
 datetime.date(2012, 6, 29),
 datetime.date(2012, 9, 28),
 datetime.date(2013, 3, 29),
 datetime.date(2013, 6, 28),
 datetime.date(2013, 8, 30),
 datetime.date(2013, 11, 29),
 datetime.date(2014, 5, 30),
 datetime.date(2014, 8, 29),
 datetime.date(2014, 11, 28),
 datetime.date(2015, 1, 30),
 datetime.date(2015, 2, 27),
 datetime.date(2015, 5, 29),
 datetime.date(2015, 10, 30),
 datetime.date(2016, 1, 29),
 datetime.date(2016, 4, 29),
 datetime.date(2016, 7, 29),
 datetime.date(2016, 12, 30),
 datetime.date(2017, 4, 28),
 datetime.date(2017, 9, 29),
 datetime.date(2017, 12, 29),
 datetime.date(2018, 3, 30),
 datetime.date(2018, 6, 29),
 datetime.date(2018, 9, 28),
 datetime.date(2019, 3, 29),
 datetime.date(2019, 6, 28),
 datetime.date(2019, 8, 30),
 datetime.date(2019, 11, 29),
 datetime.date(2020, 2, 28),
 datetime.date(2020, 5, 29),
 datetime.date(2020, 10, 30),
 datetime.date(2021, 1, 29),
 datetime.date(2021, 2, 26),
 datetime.date(2021, 7, 30),
 datetime.date(2021, 10, 29),
 datetime.date(2022, 4, 29),
 datetime.date(2022, 7, 29),
 datetime.date(2022, 12, 30)]

In [5]:
cols = [History.index] + [col for col in History.__table__.c if col.name in items]
stmt = (sa.select(*cols)
    .filter(History.__table__.c[items[0]] != None)
    .order_by(History.index.desc())
    .limit(1))
results = engine.execute(stmt)
lastHistorySource = results.first().index

In [7]:
import macrodata as md

In [8]:
from datetime import datetime as dt
from datetime import timedelta as td
from datetime import date
from pandas.tseries.offsets import CDay
end_dt = dt.now().date() - CDay(1)
start_dt = date(1970, 1, 1)
freq = 'M'
source = 'treasury'

In [9]:
tickers = session.scalars(sa.select(Data.id).where(Data.source == source)).all()

In [10]:
tickers

['us_5y_real_rate',
 'us_7y_real_rate',
 'us_10y_real_rate2',
 'us_20y_real_rate',
 'us_30y_real_rate']

In [11]:
df = md.Manager.downloadFromSource(source, tickers, start_dt, end_dt, freq)

Retrieving data from Treasury data...

In [12]:
df

,us_5y_real_rate,us_7y_real_rate,us_10y_real_rate2,us_20y_real_rate,us_30y_real_rate
Date,,,,,
2003-01-31,1.53,1.97,2.19,NaN,NaN
2003-02-28,0.94,1.48,1.77,NaN,NaN
2003-03-31,1.13,1.66,2.03,NaN,NaN
2003-04-30,1.40,1.88,2.16,NaN,NaN
2003-05-31,1.04,1.47,1.77,NaN,NaN
...,...,...,...,...,...
2022-09-30,1.92,1.77,1.68,1.68,1.74
2022-10-31,1.60,1.59,1.58,1.64,1.69
2022-11-30,1.41,1.37,1.34,1.40,1.46
2022-12-31,1.66,1.61,1.58,1.62,1.67
2023-01-31,1.36,1.31,1.28,1.36,1.43

In [13]:
items = session.scalars(sa.select(History).where(History.index.in_(df.index))).all()

In [14]:
for item in items :
    for col in df.columns :
        setattr(item, col, df.loc[item.index, col])

In [ ]:
# ADD NEW COLUMN

In [10]:
newCols = ['us_20y_real_rate',  'us_30y_real_rate',
           'us_5y_real_rate',  'us_7y_real_rate']

In [12]:
for col in newCols :
    engine.execute('ALTER TABLE monthly_history ADD COLUMN %s FLOAT' % (col))

In [9]:
histItems = session.scalars(sa.select(History).where(History.index.in_(data.index))).all()

In [12]:
for histItem in histItems :
    for col in newCols :
        setattr(histItem, col, data.loc[histItem.index, col])

In [ ]:
# **********

In [17]:
source = 'ons'
items = session.scalars(sa.select(Data).where(Data.source == source)).all()
items_ = [item.id for item in items]
cols = [History.index] + [col for col in History.__table__.c if col.name in items_]
stmt = (sa.select(*cols)
                .filter(History.__table__.c[items_[0]] != None)
                .order_by(History.index.desc())
                .limit(1))
results = engine.execute(stmt)

In [21]:
items_

['uk_cpi',
 'uk_cpi_food',
 'uk_cpi_alcohol',
 'uk_cpi_clothing',
 'uk_cpi_housing',
 'uk_cpi_furn',
 'uk_cpi_health',
 'uk_cpi_transport',
 'uk_cpi_communication',
 'uk_cpi_recreation',
 'uk_cpi_education',
 'uk_cpi_hotels',
 'uk_cpi_misc',
 'uk_retail_sales_sa',
 'uk_retail_sales_exfuel_sa',
 'uk_retail_sales_food_sa',
 'uk_retail_sales_exfood_sa',
 'uk_industrial_prod',
 'uk_gdp',
 'uk_manuf_prod',
 'uk_imports_fuel',
 'uk_exports_food',
 'uk_exports_beverages_tobacco',
 'uk_exports_materials',
 'uk_trade_balance',
 'uk_exports_animal_vegetable_oil',
 'uk_imports_beverages_tobacco',
 'uk_imports_food',
 'uk_exports_machines',
 'uk_exports_manufactures',
 'uk_exports_chemicals',
 'uk_exports_fuel',
 'uk_imports_chemicals',
 'uk_imports_animal_vegetable_oil',
 'uk_imports_manufactures',
 'uk_imports_machines',
 'uk_imports_materials']

In [18]:
for row in results :
    print(row)

In [13]:
results.first().index

AttributeError: 'NoneType' object has no attribute 'index'

In [25]:
for item in toDelete :
    session.delete(item)

In [15]:
session.add_all(items)

In [26]:
session.commit()

In [27]:
session.close()
engine.dispose()