In [1]:
import ir_curves.curves as cv
from datetime import date
from datetime import timedelta as td
import pandas as pd
import numpy as np

In [1]:
import pandas
print(pandas.__file__)

/Users/gcedism/opt/anaconda3/lib/python3.9/site-packages/pandas/__init__.py

In [2]:
pricing_dt = date(2022, 12, 20)
country = 'us'

In [3]:
us_curve = cv.Curves(country, pricing_dt)

In [4]:
us_curve.zero

               rate        df
dates
2023-01-19  4.00872  0.996671
2023-03-20  3.72473  0.990774
2023-06-18  3.16317   0.98443
2023-12-20  4.43000  0.957579
2024-12-19  4.04000  0.925241
2025-12-19  3.82000  0.897183
2027-12-19  3.58000  0.848176
2029-12-18  3.57000  0.800064
2032-12-17  3.48000   0.74184
2042-12-15  3.73000  0.572738
2052-12-12  3.53000  0.485673

In [5]:
us_curve.govt

30       3.89
60       4.23
90       4.35
120      4.55
180      4.70
365      4.64
730      4.25
1095     4.03
1825     3.79
2555     3.78
3650     3.69
7300     3.94
10950    3.74
Name: 2022-12-20, dtype: float64

In [6]:
us_curve.deposits

30     4.00872
90     3.72473
180    3.16317
Name: 2022-12-20, dtype: float64

In [7]:
new_dt = date(2022, 12, 14)
us_curve.pricing_dt = new_dt

In [8]:
us_curve.zero

               rate        df
dates
2023-01-13  3.92247  0.996742
2023-03-14  3.59298  0.991098
2023-06-12  3.06928  0.984886
2023-12-14  4.43000  0.957579
2024-12-13  4.02000  0.925583
2025-12-13  3.73000  0.899361
2027-12-13  3.43000  0.853606
2029-12-12  3.38000  0.808669
2032-12-11  3.28000  0.753012
2042-12-09  3.53000  0.586166
2052-12-06  3.31000  0.501756

In [9]:
us_curve.govt

30       3.91
60       4.14
90       4.33
120      4.58
180      4.68
365      4.64
730      4.23
1095     3.94
1825     3.64
2555     3.59
3650     3.49
7300     3.74
10950    3.52
Name: 2022-12-14, dtype: float64

In [10]:
us_curve.deposits

30     3.92247
90     3.59298
180    3.06928
Name: 2022-12-14, dtype: float64

In [16]:
import requests
import pandas as pd
import io

params = {
    'type' : 'daily_treasury_yield_curve',
    'field_tdr_date_value' : '2022',
    '_format' : 'csv'
}
p_csv = {
    'index_col': 0,
}
url = ' https://home.treasury.gov/resource-center/data-chart-center/interest-rates/daily-treasury-rates.csv/' + str(pricing_dt.year) + '/all?'
        
r = requests.get(url, params=params).content
df = pd.read_csv(io.StringIO(r.decode('utf-8')), **p_csv)

In [17]:
df

,1 Mo,2 Mo,3 Mo,4 Mo,6 Mo,1 Yr,2 Yr,3 Yr,5 Yr,7 Yr,10 Yr,20 Yr,30 Yr
Date,,,,,,,,,,,,,
12/14/2022,3.91,4.14,4.33,4.58,4.68,4.64,4.23,3.94,3.64,3.59,3.49,3.74,3.52
12/13/2022,3.89,4.16,4.35,4.58,4.70,4.64,4.22,3.96,3.66,3.60,3.51,3.74,3.53
12/12/2022,3.86,4.18,4.38,4.60,4.78,4.75,4.39,4.10,3.80,3.73,3.61,3.84,3.57
12/09/2022,3.81,4.13,4.31,4.54,4.72,4.72,4.33,4.07,3.75,3.69,3.57,3.82,3.56
12/08/2022,3.75,4.11,4.28,4.53,4.71,4.71,4.31,4.04,3.71,3.63,3.48,3.71,3.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
01/07/2022,0.05,0.05,0.10,NaN,0.24,0.43,0.87,1.17,1.50,1.69,1.76,2.15,2.11
01/06/2022,0.04,0.05,0.10,NaN,0.23,0.45,0.88,1.15,1.47,1.66,1.73,2.12,2.09
01/05/2022,0.05,0.06,0.09,NaN,0.22,0.41,0.83,1.10,1.43,1.62,1.71,2.12,2.09
01/04/2022,0.06,0.05,0.08,NaN,0.22,0.38,0.77,1.02,1.37,1.57,1.66,2.10,2.07
01/03/2022,0.05,0.06,0.08,NaN,0.22,0.40,0.78,1.04,1.37,1.55,1.63,2.05,2.01

# ***************** YAHOO **************************

In [22]:
from macrodata.clients.modules import Yahoo as yahoo_Client

In [23]:
tickers = ['aluminum_fut']

In [24]:
start_dt = date(2022, 1, 1)
end_dt = date(2023, 2, 5)
freq = 'M'

In [26]:
yahoo_Client(tickers, start_dt, end_dt, freq).data

Retrieving data from Yahoo Finance...
[*********************100%***********************]  1 of 1 completed

2021-12-31    3078.25
2022-01-31    3417.00
2022-02-28    3500.00
2022-03-31    3049.75
2022-05-31    2401.50
2022-06-30    2463.50
2022-07-31    2341.75
2022-08-31    2157.25
2022-09-30    2229.00
2022-10-31    2460.50
2022-11-30    2410.25
2023-01-31    2518.50
Name: aluminum_fut, dtype: float64

### Full Debug

In [33]:
import yfinance as yf
from datetime import datetime as dt
from datetime import timedelta as td
from datetime import date

from macrodata.clients.utils import yahoo_mapping

In [34]:
tickers = ['aluminum_fut']

In [35]:
start_dt = date(2022, 1, 1)
end_dt = date(2023, 2, 5)
freq = 'M'

In [36]:
codes = [yahoo_mapping[x] for x in tickers]

In [37]:
y_params = {
    'tickers': codes,
    'start': start_dt,
    'end': end_dt,
    'interval': '1mo'
}
data = yf.download(**y_params)['Adj Close']

[*********************100%***********************]  1 of 1 completed

In [38]:
data

Date
2022-01-01    3078.25
2022-02-01    3417.00
2022-03-01    3500.00
2022-04-01    3049.75
2022-06-01    2401.50
2022-07-01    2463.50
2022-08-01    2341.75
2022-09-01    2157.25
2022-10-01    2229.00
2022-11-01    2460.50
2022-12-01    2410.25
2023-02-01    2518.50
Name: Adj Close, dtype: float64

# ***************** EUROSTAT **************************

In [1]:
import json
from datetime import date
from datetime import datetime as dt
from datetime import timedelta as td

In [2]:
sec = json.load(open('macrodata/data_specs.json'))
tickers = [x for x in sec if sec[x]['source']['name'] == 'ec']

In [3]:
tickers

['eu_ind_conf',
 'eu_ind_inventories',
 'eu_retail_sales',
 'eu_retail_sales_real',
 'de_ind_conf',
 'fr_ind_conf',
 'uk_ind_conf',
 'eu_ca',
 'de_ca',
 'fr_ca',
 'uk_ca',
 'eu_ind_prod',
 'de_ind_prod',
 'fr_ind_prod',
 'uk_ind_prod']

### Using the Client

In [4]:
from macrodata.eurostat import Client as ec_Client

In [5]:
end_dt = dt.now().date()
start_dt = end_dt - td(days=180)
freq = 'M'

In [6]:
ec_Client(tickers, start_dt, end_dt, freq).data

Retrieving data from Eurostat Data...
No data for uk_ind_conf
No data for uk_ca
No data for uk_ind_prod

,eu_ind_conf,eu_ind_inventories,eu_retail_sales,eu_retail_sales_real,de_ind_conf,fr_ind_conf,eu_ca,de_ca,fr_ca,eu_ind_prod,de_ind_prod,fr_ind_prod
TIME_PERIOD,,,,,,,,,,,,
2022-08-31,0.3,4.8,0.4,0.0,7.8,-4.7,-25095.9,880.0,-9932.0,109.6,94.9,99.9
2022-09-30,-1.0,4.4,1.3,0.8,4.5,-6.5,-20136.4,11695.0,-5235.0,110.3,96.1,99.1
2022-10-31,-1.7,7.0,-0.5,-1.4,3.4,-6.7,-2906.2,5671.0,-6011.0,108.2,95.1,96.4
2022-11-30,-2.3,7.8,1.2,0.9,3.6,-9.1,18827.6,16883.0,-1674.0,109.2,95.7,98.3
2022-12-30,-1.4,8.8,NaN,NaN,3.3,-8.4,NaN,NaN,NaN,NaN,NaN,99.4
2023-01-31,0.3,7.0,NaN,NaN,4.4,-5.8,NaN,NaN,NaN,NaN,NaN,NaN

### Full Debug

In [12]:
import io
import requests
import pandas as pd
import numpy as np
from datetime import datetime as dt
from macrodata.eurostat.utils import ticker_map, EoXMonth

In [33]:
p = {
    'format': 'SDMX-CSV',
    'lang': 'en',
    'detail': 'dataonly',
    'startPeriod': date.strftime(start_dt, '%Y-%m')
}
url = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/'

data = []

In [15]:
# Using For loop
for tic in tickers :
    url_f = url + ticker_map[tic]['flow'] + ticker_map[tic]['filter']

    _s = requests.get(url_f, p).content
    df = pd.read_csv(io.StringIO(_s.decode('utf-8')))
    print(tic)
    _data = df.pivot_table(values='OBS_VALUE', index='TIME_PERIOD', columns='geo', aggfunc=np.sum)
    _data.columns = [tic]
    _data.index = _data.index.map(lambda x: EoXMonth(dt.strptime(x, '%Y-%m').date(), 0))
    data.append(_data)

eu_ind_conf
eu_ind_inventories
eu_retail_sales
eu_retail_sales_real
de_ind_conf
fr_ind_conf
uk_ind_conf

KeyError: 'OBS_VALUE'

In [19]:
# No For Loop
tic = 'fr_ind_conf'
url_f = url + ticker_map[tic]['flow'] + ticker_map[tic]['filter']

In [34]:
url_f = 'https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/ei_bsin_m_r2/M.BS-ICI.SA.BAL.UK'

In [35]:
_s = requests.get(url_f, p).content
df = pd.read_csv(io.StringIO(_s.decode('utf-8')))

In [ ]:
_data = df.pivot_table(values='OBS_VALUE', index='TIME_PERIOD', columns='geo', aggfunc=np.sum)
_data.columns = [tic]
_data.index = _data.index.map(lambda x: EoXMonth(dt.strptime(x, '%Y-%m').date(), 0))
data.append(_data)

In [37]:
df.empty

True

# ***************** BLS **************************

In [8]:
from macroData.macrodata.bls import Client as bls_Client

In [9]:
from datetime import date as dt

In [10]:
start = dt(1970, 1, 1)
end = dt(2022, 11, 1)

In [11]:
tickers = ['us_cpi', 'us_cpi_core']

In [12]:
b = bls_Client(tickers, start, end, 'M')

Retrieving data from BLS - Bureau of Labour Statistics...

In [13]:
b.data

             us_cpi us_cpi_core
1970-01-31     37.8        39.6
1970-02-28     38.0        39.8
1970-03-31     38.2        40.1
1970-04-30     38.5        40.3
1970-05-31     38.6        40.5
...             ...         ...
2022-06-30  296.311     294.680
2022-07-31  296.276     295.646
2022-08-31  296.171     297.178
2022-09-30  296.808     298.442
2022-10-31  298.012     299.315

[634 rows x 2 columns]

In [1]:
import json
import macroData.macrodata as md
from datetime import date
from datetime import datetime as dt

In [2]:
sec = json.load(open('macroData/macrodata/data_specs.json'))

In [3]:
selections = ['us_cpi', 'us_cpi_core']

In [4]:
sel_sec = {x:sec[x] for x in selections}
start = date(1970, 1, 1)
end = date(2022, 11, 1)

In [5]:
data = md.Database(sel_sec, start, end, 'M').data

Retrieving data from BLS - Bureau of Labour Statistics...

In [6]:
data

             us_cpi us_cpi_core
1970-01-31     37.8        39.6
1970-02-28     38.0        39.8
1970-03-31     38.2        40.1
1970-04-30     38.5        40.3
1970-05-31     38.6        40.5
...             ...         ...
2022-06-30  296.311     294.680
2022-07-31  296.276     295.646
2022-08-31  296.171     297.178
2022-09-30  296.808     298.442
2022-10-31  298.012     299.315

[634 rows x 2 columns]

# *************** FRED ****************************

In [2]:
from macrodata.fred import Client as fred_Client
from datetime import date as dt

start = dt(2022, 1, 1)
end = dt(2023, 1, 31)

tickers = ['us_M1',
 'us_michigan_cons_conf',
 'us_IG_spread',
 'us_BBB_spread',
 'us_BB_spread',
 'us_HY_spread',
 'us_A_spread',
 'us_AA_spread',
 'us_B_spread',
 'us_EM_spread',
 'us_10y_real_rate',
 'us_5v5_inflation',
 'us_5y_be_inflation',
 'eu_hcpi',
 'eu_hcpi_core',
 'can_cpi',
 'nor_cpi',
 'swe_cpi',
 'pol_cpi',
 'hun_cpi',
 'czk_cpi',
 'zar_cpi',
 'can_3m_rate']



b = fred_Client(tickers, start, end, 'M')

Retrieving data from FRED - FED St Louis Economic Data...

In [3]:
b.data

,us_M1,us_michigan_cons_conf,us_IG_spread,us_BBB_spread,us_BB_spread,us_HY_spread,us_A_spread,us_AA_spread,us_B_spread,us_EM_spread,...,eu_hcpi,eu_hcpi_core,can_cpi,nor_cpi,swe_cpi,pol_cpi,hun_cpi,czk_cpi,zar_cpi,can_3m_rate
2022-01-31,20585.5,67.2,1.10,1.34,2.66,3.63,0.89,0.72,3.96,2.97,...,5.1,106.73,113.778608,117.8,111.876388,121.367521,123.760178,124.6,135.298751,0.457195
2022-02-28,20661.0,62.8,1.30,1.60,2.75,3.77,1.05,0.82,4.11,3.64,...,5.9,107.30,114.819510,119.1,112.833797,121.041921,125.092524,126.2,136.108923,0.620984
2022-03-31,20699.1,59.4,1.22,1.49,2.37,3.43,0.99,0.74,3.77,3.03,...,7.4,108.59,116.100621,119.8,114.825206,125.030525,126.350851,128.3,137.594239,0.875735
2022-04-30,20617.6,65.2,1.41,1.71,2.85,3.97,1.17,0.86,4.21,3.00,...,7.4,109.73,116.901314,121.2,115.533689,127.553928,128.349371,130.6,138.404411,1.346640
2022-05-31,20627.6,58.4,1.40,1.73,2.74,4.22,1.13,0.83,4.67,3.18,...,8.1,110.25,118.422633,121.5,116.746406,129.751730,130.495929,132.9,139.349612,1.781894
2022-06-30,20556.5,50.0,1.64,2.04,4.17,5.87,1.32,0.96,6.52,3.66,...,8.6,110.50,119.543604,122.6,118.383575,131.705332,132.420429,135.0,140.834927,2.247345
2022-07-31,20532.6,51.5,1.53,1.92,3.18,4.83,1.22,0.86,5.38,3.67,...,8.9,110.33,119.543604,124.2,118.488890,132.356532,135.529238,136.8,143.130415,3.014111
2022-08-31,20472.4,58.2,1.48,1.85,3.44,5.03,1.19,0.85,5.27,3.34,...,9.1,110.92,119.783813,123.9,120.572849,133.414733,137.971873,137.4,143.535501,3.382213
2022-09-30,20283.4,58.6,1.67,2.06,3.66,5.43,1.38,0.96,5.74,3.57,...,9.9,111.98,119.863882,125.6,122.296185,135.531136,143.597335,138.5,143.670530,3.791927
2022-10-31,20100.3,59.9,1.66,2.03,2.95,4.63,1.40,0.92,4.83,3.72,...,10.6,112.60,120.584507,126.0,122.561068,137.973138,146.484086,136.5,144.075616,4.230834
2022-11-30,19935.8,56.8,1.42,1.77,2.97,4.55,1.17,0.77,4.79,3.22,...,10.1,112.60,121.225062,125.8,123.802508,138.949939,149.148779,138.1,144.615731,4.376342
2022-12-31,19685.8,59.7,1.38,1.72,3.08,4.81,1.14,0.77,5.15,2.95,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.550000
2023-01-31,NaN,NaN,1.25,1.56,2.80,4.30,1.02,0.73,4.55,2.72,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['us_M1', 'us_michigan_cons_conf', 'us_cpi']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from BLS - Bureau of Labour Statistics...
Retrieving data from FRED - FED St Louis Economic Data...

In [7]:
d.data

             us_cpi    us_M1  us_michigan_cons_conf
1970-01-31     37.8    206.2                    0.0
1970-02-28     38.0    205.0                   78.1
1970-03-31     38.2    205.7                    0.0
1970-04-30     38.5    206.7                    0.0
1970-05-31     38.6    207.2                   75.4
...             ...      ...                    ...
2022-06-30  296.311  20556.7                   50.0
2022-07-31  296.276  20532.6                   51.5
2022-08-31  296.171  20472.7                   58.2
2022-09-30  296.808  20283.6                   58.6
2022-10-31  298.012  20099.9                   59.9

[634 rows x 3 columns]

# ******* TREASURY *******

In [1]:
from datetime import date
from macrodata.clients.modules import Treasury as treasury_Client

In [2]:
start_dt = date(1980, 1, 1)
end_dt = date(1990, 1, 31)

tickers = ['us_5y_real_rate',
 'us_7y_real_rate',
 'us_10y_real_rate2',
 'us_20y_real_rate',
 'us_30y_real_rate']

In [3]:
treasury_Client(tickers, start_dt, end_dt, freq='M').data

Retrieving data from Treasury data...

EmptyDataError: No columns to parse from file

### Manual Debut

In [5]:
import io
import requests
import pandas as pd

from datetime import date

In [19]:
start_dt = date(2021, 1, 1)
end_dt = date(1990, 1, 31)
year = start_dt.year

tickers = ['us_5y_real_rate',
 'us_7y_real_rate',
 'us_10y_real_rate2',
 'us_20y_real_rate',
 'us_30y_real_rate']

In [20]:
params = {
    'type' : 'daily_treasury_real_yield_curve',
    'field_tdr_date_value' : str(year),
    '_format' : 'csv'
}
p_csv = {
    'index_col': 0,
}
                    
url = 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/daily-treasury-rates.csv/' + str(year) + '/all?'
        
r = requests.get(url, params=params)

In [ ]:
_df = pd.read_csv(io.StringIO(r.decode('utf-8')), **p_csv)
if not _df.empty :
    dfs.append(_df)

In [ ]:
_data = []
        _temp = {}
        for tic in self._tickers :
            
            if 'treasury' not in _temp.keys() :
                dfs = []
                for year in range(self._start_dt.year, self._end_dt.year+1) :
                    params = {
                        'type' : 'daily_treasury_real_yield_curve',
                        'field_tdr_date_value' : str(year),
                        '_format' : 'csv'
                    }
                    p_csv = {
                        'index_col': 0,
                    }
                    
                    url = 'https://home.treasury.gov/resource-center/data-chart-center/interest-rates/daily-treasury-rates.csv/' + str(year) + '/all?'
        
                    r = requests.get(url, params=params).content
                    _df = pd.read_csv(io.StringIO(r.decode('utf-8')), **p_csv)
                    if not _df.empty :
                        dfs.append(_df)
                
                df = pd.concat(dfs)
                df.index = df.index.map(lambda x : dt.strptime(x, '%m/%d/%Y').date())
                df.columns = ['us_5y_real_rate', 'us_7y_real_rate',
                             'us_10y_real_rate2', 'us_20y_real_rate',
                             'us_30y_real_rate']
                _temp['treasury'] = df.sort_index()
                
            final_df = pd.DataFrame(_temp['treasury'].loc[:, tic])
            _data.append(final_df)
            
        final_data = _data[0].join(_data[1:], how='outer')
        if self._freq == 'M' :
            final = final_data.loc[[isEndOfMonth(x) for x in final_data.index]]
            # Correct data to last calendar day to match other time series
            final.index = final.index.map(lambda x : EoXMonth(x, 0, False))
            self._data = final
        else :
            self._data = final_data

# *** CENSUS ***

In [1]:
from macroData.macrodata.census import Client as census_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['us_durable_goods_new_orders', 'us_durable_goods_shipments']

b = census_Client(tickers, start, end, 'M')

Retrieving data from Census...

In [2]:
b.data

            us_durable_goods_new_orders  us_durable_goods_shipments
1970-01-31                          NaN                         NaN
1970-02-28                          NaN                         NaN
1970-03-31                          NaN                         NaN
1970-04-30                          NaN                         NaN
1970-05-31                          NaN                         NaN
...                                 ...                         ...
2022-08-31                     273841.0                    273530.0
2022-09-30                     274557.0                    274331.0
2022-10-31                     277375.0                    275396.0
2022-11-30                          NaN                         NaN
2022-12-31                          NaN                         NaN

[636 rows x 2 columns]

SyntaxError: invalid syntax (3808738073.py, line 1)

In [3]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['us_durable_goods_new_orders', 'us_durable_goods_shipments', 'us_cpi']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from BLS - Bureau of Labour Statistics...
Retrieving data from Census...

In [4]:
d.data

             us_cpi  us_durable_goods_new_orders  us_durable_goods_shipments
1970-01-31     37.8                          NaN                         NaN
1970-02-28     38.0                          NaN                         NaN
1970-03-31     38.2                          NaN                         NaN
1970-04-30     38.5                          NaN                         NaN
1970-05-31     38.6                          NaN                         NaN
...             ...                          ...                         ...
2022-08-31  296.171                     273841.0                    273530.0
2022-09-30  296.808                     274557.0                    274331.0
2022-10-31  298.012                     277375.0                    275396.0
2022-11-30      NaN                          NaN                         NaN
2022-12-31      NaN                          NaN                         NaN

[636 rows x 3 columns]

In [1]:
from macroData.macrodata.bea import Client as bea_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['us_pers_spending', 'us_pce']

b = bea_Client(tickers, start, end, 'Q')

Retrieving data from BEA - Bureau of Economic Analyses...

In [2]:
b.data

           us_pers_spending   us_pce
TimePeriod
1970-03-31              NaN   20.570
1970-06-30              NaN   20.798
1970-09-30              NaN   21.000
1970-12-31              NaN   21.272
1971-03-31              NaN   21.474
...                     ...      ...
2020-12-31       13,046,614  111.821
2021-03-31       13,386,763  113.059
2021-06-30       13,773,688  114.838
2021-09-30       13,874,396  116.413
2021-12-31       13,981,514  118.173

[208 rows x 2 columns]

In [3]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['us_pce']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'Q')

Retrieving data from BEA - Bureau of Economic Analyses...

In [4]:
d.data

             us_pce
1970-03-31   20.570
1970-06-30   20.798
1970-09-30   21.000
1970-12-31   21.272
1971-03-31   21.474
...             ...
2021-09-30  116.413
2021-12-31  118.173
2022-03-31      NaN
2022-06-30      NaN
2022-09-30      NaN

[211 rows x 1 columns]

In [1]:
from macroData.macrodata.fed import Client as fed_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['us_ip_sa']

In [2]:
b = fed_Client(tickers, start, end, 'M')

Retrieving data from FED...

In [3]:
b.data

            us_ip_sa
1970-01-31   38.0213
1970-02-28   37.9963
1970-03-31   37.9469
1970-04-30   37.8494
1970-05-31   37.8053
...              ...
2021-08-31  100.8370
2021-09-30   99.8498
2021-10-31  101.3602
2021-11-30  101.9610
2021-12-31  101.7587

[624 rows x 1 columns]

In [1]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['us_ip_sa']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from FED...

In [3]:
d.data

            us_ip_sa
1970-01-31   38.0213
1970-02-28   37.9963
1970-03-31   37.9469
1970-04-30   37.8494
1970-05-31   37.8053
...              ...
2022-06-30       NaN
2022-07-31       NaN
2022-08-31       NaN
2022-09-30       NaN
2022-10-31       NaN

[634 rows x 1 columns]

In [1]:
from macroData.macrodata.ons import Client as ons_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

# tickers = ['uk_cpi', 'uk_retail_sales_sa', 'uk_retail_sales_exfuel_sa', 'uk_trade_balance', 'uk_exports_manufactures', 'uk_imports_animal_vegetable_oil']
tickers = ['uk_cpi', 'uk_retail_sales_sa', 'uk_retail_sales_exfuel_sa', 'uk_trade_balance']

In [2]:
b = ons_Client(tickers, start, end, 'M')

Retrieving data from ONS - Office for National Statistics...
Dowloading whole group...inflation
Usecols are : [0, 27]

/Users/gcedism/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Using col names: ['uk_cpi']
Data Group inflation downloaded
Dowloading whole group...retail_sales
Usecols are : [0, 1, 2, 3, 4]
Using col names: ['uk_retail_sales_sa', 'uk_retail_sales_exfuel_sa', 'uk_retail_sales_food_sa', 'uk_retail_sales_exfood_sa']
Data Group retail_sales downloaded
Data group retail_sales already dowloaded
Dowloading whole group...trade
Usecols are : [0, 103, 224, 248, 300, 314, 348, 369, 379, 393, 406, 419, 522, 612, 755, 760, 769, 988]

/Users/gcedism/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

Using col names: ['uk_imports_fuel', 'uk_exports_food', 'uk_exports_beverages_tobacco', 'uk_exports_materials', 'uk_trade_balance', 'uk_exports_animal_vegetable_oil', 'uk_imports_beverages_tobacco', 'uk_imports_food', 'uk_exports_machines', 'uk_exports_manufactures', 'uk_exports_chemicals', 'uk_exports_fuel', 'uk_imports_chemicals', 'uk_imports_animal_vegetable_oil', 'uk_imports_manufactures', 'uk_imports_machines', 'uk_imports_materials']
Data Group trade downloaded

In [3]:
b.data

,uk_cpi,uk_retail_sales_sa,uk_retail_sales_exfuel_sa,uk_trade_balance
1993-01-29,62.8,NaN,51.8,NaN
1993-02-26,63.2,NaN,51.9,NaN
1993-03-31,63.6,NaN,51.9,NaN
1993-04-30,64.3,NaN,51.8,NaN
1993-05-31,64.5,NaN,51.7,NaN
...,...,...,...,...
2022-06-30,121.8,101,102.3,-9174.0
2022-07-29,122.5,101.1,102.4,-7427.0
2022-08-31,123.1,99.5,100.7,-7266.0
2022-09-30,123.8,98,99.2,-9254.0
2022-10-31,126.2,98.6,99.6,NaN

In [1]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['uk_cpi']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from ONS - Office for National Statistics...
Dowloading whole group...inflation
Usecols are : [0, 27]
Using col names: ['uk_cpi']
Data Group inflation downloaded

In [5]:
d.data

,uk_cpi,uk_retail_sales_sa,uk_retail_sales_exfuel_sa,uk_trade_balance,uk_exports_manufactures,uk_imports_animal_vegetable_oil
1970-01-31,NaN,NaN,NaN,NaN,NaN,NaN
1970-02-28,NaN,NaN,NaN,NaN,NaN,NaN
1970-03-31,NaN,NaN,NaN,NaN,NaN,NaN
1970-04-30,NaN,NaN,NaN,NaN,NaN,NaN
1970-05-31,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
2022-07-29,122.5,101.1,102.4,-7427.0,12129.0,-228.0
2022-07-31,NaN,NaN,NaN,NaN,NaN,NaN
2022-08-31,123.1,99.5,100.7,-7266.0,12719.0,-194.0
2022-09-30,123.8,98,99.2,-9254.0,11602.0,-121.0
2022-10-31,126.2,98.6,99.6,NaN,NaN,NaN

In [1]:
from macroData.macrodata.bcb import Client as bcb_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['bra_ipca_MoM', 'bra_reserves']

In [2]:
b = bcb_Client(tickers, start, end, 'M')

Retrieving data from BCB...
Downloading
Already Downloaded

In [3]:
b.data

           bra_ipca_MoM bra_reserves
1970-12-31         None         1187
1971-01-29         None         1229
1971-02-26         None         1280
1971-03-31         None         1316
1971-04-30         None         1379
...                 ...          ...
2022-06-30         0.67       341958
2022-07-29        -0.68       346403
2022-08-31        -0.36       339664
2022-09-30        -0.29       327580
2022-10-31         0.59       325546

[623 rows x 2 columns]

In [1]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['bra_ipca_MoM', 'bra_reserves']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from BCB...
Downloading
Already Downloaded

In [2]:
d.data

           bra_ipca_MoM bra_reserves
1970-01-31          NaN          NaN
1970-02-28          NaN          NaN
1970-03-31          NaN          NaN
1970-04-30          NaN          NaN
1970-05-31          NaN          NaN
...                 ...          ...
2022-07-29        -0.68       346403
2022-07-31          NaN          NaN
2022-08-31        -0.36       339664
2022-09-30        -0.29       327580
2022-10-31         0.59       325546

[811 rows x 2 columns]

In [1]:
from macroData.macrodata.eurostat import Client as es_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['eu_ind_conf', 'eu_retail_sales']

b = es_Client(tickers, start, end, 'M')

Retrieving data from Eurostat Data...

In [2]:
b.data

             eu_ind_conf  eu_retail_sales
TIME_PERIOD
1980-01-31          -2.5              NaN
1980-02-29          -2.7              NaN
1980-03-31          -4.3              NaN
1980-04-30          -8.4              NaN
1980-05-30         -12.2              NaN
...                  ...              ...
2022-07-29           1.9              0.5
2022-08-31           0.6              0.4
2022-09-30          -1.3              1.1
2022-10-31          -2.5              NaN
2022-11-30          -3.2              NaN

[515 rows x 2 columns]

In [3]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['eu_ind_conf', 'eu_retail_sales']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from Eurostat Data...

In [4]:

d.data

            eu_ind_conf  eu_retail_sales
1970-01-31          NaN              NaN
1970-02-28          NaN              NaN
1970-03-31          NaN              NaN
1970-04-30          NaN              NaN
1970-05-31          NaN              NaN
...                 ...              ...
2022-07-31          NaN              NaN
2022-08-31          0.6              0.4
2022-09-30         -1.3              1.1
2022-10-31         -2.5              NaN
2022-11-30         -3.2              NaN

[737 rows x 2 columns]

## INEGI (MEXICO)

In [1]:
from macrodata.clients.inegi import Client as inegi_Client
from datetime import date

In [2]:
start_dt = date(1970, 1, 1)
end_dt = date(2022, 11, 1)

tickers = ['mxn_cpi_mom', 'mxn_cons_conf']

b = inegi_Client(tickers, start_dt, end_dt, 'M')

In [3]:
b.data

            mxn_cpi_mom    mxn_cons_conf
TIME_PERIOD
1970-01-31         0.76              NaN
1970-02-28        -0.01              NaN
1970-03-31         0.29              NaN
1970-04-30         0.13              NaN
1970-05-31         0.21              NaN
...                 ...              ...
2022-10-31         0.57  41.283880015539
2022-11-30         0.58  41.755955250832
2022-12-31         0.38  43.287305150133
2023-01-31         0.68  44.774005908794
2023-02-28         0.56  44.648579360698

[638 rows x 2 columns]

### manual INEGI

In [1]:
import macrodata as md
import pandas as pd
import requests
import json

from datetime import date
from datetime import datetime as dt

from macrodata.clients.inegi.utils import ticker_map, EoXMonth
from macrodata.clients.inegi.utils_private import API_KEYS

In [41]:
tickers = md.Explorer.countryList(['Mexico'])['Mexico']

In [42]:
tickers

['MXN=X', 'mxn_cpi_mom', 'mxn_cons_conf']

In [43]:
start_dt = date(1970, 1, 1)
end_dt = date(2022, 11, 1)

In [44]:
def _get_inegi(tickers:list[str], start_dt, end_dt) -> pd.DataFrame:
        _data = []
        p = {'type': 'json'}
        
        for tic in tickers:
            url = ('http://en.www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/'
            + ticker_map[tic]['id'] 
            + '/en/0700/false/' 
            + ticker_map[tic]['fuente'] 
            + '/2.0/' 
            + API_KEYS['INEGI_API_KEY'])
            s = requests.get(url, p).text
            _d = pd.DataFrame(json.loads(s)['Series'][0]['OBSERVATIONS']).set_index('TIME_PERIOD')
            _d.index = _d.index.map(lambda x: EoXMonth(dt.strptime(x, '%Y/%m').date(), 0, False))
            _d = _d.loc[_d.index >= start_dt].sort_index()['OBS_VALUE']
            _d.name = tic
            _data.append(pd.DataFrame(_d))

        _data = _data[0].join(_data[1:], how='outer')
        return _data

In [45]:
_get_inegi(tickers[1:], start_dt, end_dt)

            mxn_cpi_mom    mxn_cons_conf
TIME_PERIOD
1970-01-31         0.76              NaN
1970-02-28        -0.01              NaN
1970-03-31         0.29              NaN
1970-04-30         0.13              NaN
1970-05-31         0.21              NaN
...                 ...              ...
2022-10-31         0.57  41.283880015539
2022-11-30         0.58  41.755955250832
2022-12-31         0.38  43.287305150133
2023-01-31         0.68  44.774005908794
2023-02-28         0.56  44.648579360698

[638 rows x 2 columns]

In [ ]:
# Tests

In [50]:
catalogue = ['CL_STATUS', 
            'CL_GEO_AREA', 
            'CL_SOURCE', 
            'CL_FREQ',
            'CL_NOTE',
            'CL_INDICATOR',
            'CL_TOPIC',
            'CL_UNIT']
sources = ['BISE', 'BIE']
idCatalog = ['1', 'null']
language = ['es', 'en']

In [15]:
p = {'type': 'json'}
catalogue = 'CL_INDICATOR'
idCatalog = 'null'
language = 'en'
source = 'BIE'
version = '2.0'
url = ('https://www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/'
       + catalogue + '/'
       + idCatalog + '/'
       + language + '/'
       + source + '/'
       + version + '/'
       + API_KEYS['INEGI_API_KEY'])

In [16]:
s = requests.get(url, p).text

In [17]:
json.loads(s)

{'id': 'CL_INDICATOR',
 'agencyID': 'INEGI',
 'version': '1.0',
 'lang': 'en',
 'CODE': [{'value': '1', 'Description': 'Serie original'},
  {'value': '3', 'Description': 'Serie desestacionalizada'},
  {'value': '5', 'Description': 'Tendencia-ciclo'},
  {'value': '11', 'Description': 'Aguascalientes'},
  {'value': '12', 'Description': 'Baja California'},
  {'value': '13', 'Description': 'Coahuila de Zaragoza'},
  {'value': '14', 'Description': 'Distrito Federal'},
  {'value': '15', 'Description': 'Durango'},
  {'value': '16', 'Description': 'Jalisco'},
  {'value': '17', 'Description': 'México'},
  {'value': '18', 'Description': 'Morelos'},
  {'value': '19', 'Description': 'Nuevo León'},
  {'value': '20', 'Description': 'Puebla'},
  {'value': '21', 'Description': 'Querétaro'},
  {'value': '22', 'Description': 'San Luis Potosí'},
  {'value': '23', 'Description': 'Sinaloa'},
  {'value': '24', 'Description': 'Sonora'},
  {'value': '25', 'Description': 'Tlaxcala'},
  {'value': '26', 'Description': 'Veracruz de Ignacio de la Llave'},
  {'value': '27', 'Description': 'Yucatán'},
  {'value': '62', 'Description': 'Aguascalientes'},
  {'value': '63', 'Description': 'Baja California'},
  {'value': '64', 'Description': 'Coahuila de Zaragoza'},
  {'value': '65', 'Description': 'Distrito Federal'},
  {'value': '66', 'Description': 'Durango'},
  {'value': '67', 'Description': 'Jalisco'},
  {'value': '68', 'Description': 'México'},
  {'value': '69', 'Description': 'Morelos'},
  {'value': '70', 'Description': 'Nuevo León'},
  {'value': '71', 'Description': 'Puebla'},
  {'value': '72', 'Description': 'Querétaro'},
  {'value': '73', 'Description': 'San Luis Potosí'},
  {'value': '74', 'Description': 'Sinaloa'},
  {'value': '75', 'Description': 'Sonora'},
  {'value': '76', 'Description': 'Tlaxcala'},
  {'value': '77', 'Description': 'Veracruz de Ignacio de la Llave'},
  {'value': '78', 'Description': 'Yucatán'},
  {'value': '241', 'Description': 'Formación bruta de capital fijo total'},
  {'value': '242', 'Description': 'Total'},
  {'value': '243', 'Description': 'Nacional'},
  {'value': '244', 'Description': 'Importado'},
  {'value': '245',
   'Description': 'Formación bruta de capital fijo en construcción'},
  {'value': '431', 'Description': 'Total'},
  {'value': '432', 'Description': 'Producto interno bruto'},
  {'value': '433', 'Description': 'Importación de bienes y servicios'},
  {'value': '440', 'Description': 'Total'},
  {'value': '441', 'Description': 'Consumo privado'},
  {'value': '442', 'Description': 'Consumo de gobierno'},
  {'value': '443', 'Description': 'Formación bruta de capital fijo'},
  {'value': '444', 'Description': 'Variación de existencias'},
  {'value': '445', 'Description': 'Exportación de bienes y servicios'},
  {'value': '465', 'Description': 'Total'},
  {'value': '466', 'Description': 'Minería'},
  {'value': '467', 'Description': 'Total'},
  {'value': '468', 'Description': 'Industria maquiladora de exportación'},
  {'value': '469', 'Description': 'Industria de la transformación'},
  {'value': '470', 'Description': 'Construcción'},
  {'value': '471', 'Description': 'Electricidad, gas y agua'},
  {'value': '486', 'Description': 'Total'},
  {'value': '487',
   'Description': 'I   Productos alimenticios, bebidas y tabaco'},
  {'value': '488',
   'Description': 'II   Textiles, prendas de vestir e industria del cuero'},
  {'value': '489',
   'Description': 'III Industria de la madera y productos de madera'},
  {'value': '490',
   'Description': 'IV   Papel, productos de papel, imprentas y editoriales'},
  {'value': '491',
   'Description': 'V     Sustancias químicas, derivados del petróleo, productos de caucho y plástico'},
  {'value': '492',
   'Description': 'VI   Productos de minerales no metálicos, excepto derivados del petróleo y carbón'},
  {'value': '493', 'Description': 'VII Industrias metálicas básicas'},
  {'value': '494',
   'Description': 'VIII Productos metálicos, maquinaria y equipo'},
  {'value': '495', 'Description': 'IX   Otras industrias manufactureras'},
  {'value': '516', 'Description': 'Bienes de demanda intermedia'},
  {'value': '519', 'Description': 'Bienes de consumo final'},
  {'value': '522', 'Description': 'Bienes de capital'},
  {'value': '656', 'Description': 'Índice'},
  {'value': '657', 'Description': 'Variación anual'},
  {'value': '658', 'Description': 'Variación anual acumulada'},
  {'value': '659', 'Description': 'Oro'},
  {'value': '660', 'Description': 'Plata'},
  {'value': '661', 'Description': 'Oro'},
  {'value': '662', 'Description': 'Plata'},
  {'value': '663', 'Description': 'Oro'},
  {'value': '664', 'Description': 'Plata'},
  {'value': '665', 'Description': 'Plomo'},
  {'value': '666', 'Description': 'Cobre'},
  {'value': '667', 'Description': 'Zinc'},
  {'value': '668', 'Description': 'Plomo'},
  {'value': '669', 'Description': 'Cobre'},
  {'value': '670', 'Description': 'Zinc'},
  {'value': '671', 'Description': 'Plomo'},
  {'value': '672', 'Description': 'Cobre'},
  {'value': '673', 'Description': 'Zinc'},
  {'value': '674', 'Description': 'Carbón mineral no coquizable'},
  {'value': '675', 'Description': 'Coque'},
  {'value': '676', 'Description': 'Pellets de fierro'},
  {'value': '677', 'Description': 'Carbón mineral no coquizable'},
  {'value': '678', 'Description': 'Coque'},
  {'value': '679', 'Description': 'Pellets de fierro'},
  {'value': '680', 'Description': 'Carbón mineral no coquizable'},
  {'value': '681', 'Description': 'Coque'},
  {'value': '682', 'Description': 'Pellets de fierro'},
  {'value': '683', 'Description': 'Azufre'},
  {'value': '684', 'Description': 'Dolomita'},
  {'value': '685', 'Description': 'Fluorita'},
  {'value': '686', 'Description': 'Arena sílica'},
  {'value': '687', 'Description': 'Yeso'},
  {'value': '688', 'Description': 'Fosforita'},
  {'value': '689', 'Description': 'Azufre'},
  {'value': '690', 'Description': 'Dolomita'},
  {'value': '691', 'Description': 'Fluorita'},
  {'value': '692', 'Description': 'Arena sílica'},
  {'value': '693', 'Description': 'Yeso'},
  {'value': '694', 'Description': 'Fosforita'},
  {'value': '695', 'Description': 'Azufre'},
  {'value': '696', 'Description': 'Dolomita'},
  {'value': '697', 'Description': 'Fluorita'},
  {'value': '698', 'Description': 'Arena sílica'},
  {'value': '699', 'Description': 'Yeso'},
  {'value': '700', 'Description': 'Fosforita'},
  {'value': '799', 'Description': 'Índice general'},
  {'value': '800', 'Description': 'Índice general'},
  {'value': '801', 'Description': 'Índice general'},
  {'value': '802', 'Description': 'Índice general'},
  {'value': '807', 'Description': 'Índice'},
  {'value': '808', 'Description': 'Inflación quincenal'},
  {'value': '897', 'Description': 'Total'},
  {'value': '912', 'Description': 'Total'},
  {'value': '913', 'Description': 'Petróleo crudo'},
  {'value': '914', 'Description': 'Otras'},
  {'value': '915', 'Description': 'Total'},
  {'value': '916', 'Description': 'Petróleo crudo'},
  {'value': '917', 'Description': 'Otras'},
  {'value': '918', 'Description': 'Total'},
  {'value': '919', 'Description': 'Petróleo crudo'},
  {'value': '920', 'Description': 'Otras'},
  {'value': '921', 'Description': 'Total'},
  {'value': '922', 'Description': 'Agropecuarias'},
  {'value': '923', 'Description': 'Extractivas'},
  {'value': '924', 'Description': 'Total'},
  {'value': '925', 'Description': 'Total'},
  {'value': '926', 'Description': 'Agropecuarias'},
  {'value': '927', 'Description': 'Extractivas'},
  {'value': '929', 'Description': 'Total'},
  {'value': '930', 'Description': 'Agropecuarias'},
  {'value': '931', 'Description': 'Extractivas'},
  {'value': '932', 'Description': 'Total'},
  {'value': '933', 'Description': 'Total'},
  {'value': '934', 'Description': 'Total'},
  {'value': '935', 'Description': 'Bienes de capital'},
  {'value': '936', 'Description': 'Total'},
  {'value': '937', 'Description': 'Total'},
  {'value': '938', 'Description': 'Bienes de capital'},
  {'value': '939', 'Description': 'Total'},
  {'value': '940', 'Description': 'Total'},
  {'value': '941', 'Description': 'Bienes de capital'},
  {'value': '942', 'Description': 'Total'},
  {'value': '943',
   'Description': 'Impuestos a los productos netos de subsidios'},
  {'value': '944', 'Description': 'Valor agregado bruto en valores básicos'},
  {'value': '945', 'Description': '1 Agropecuario, silvicultura y pesca'},
  {'value': '946', 'Description': '2 Minería'},
  {'value': '947', 'Description': '3 Industria manufacturera'},
  {'value': '948', 'Description': '4 Construcción'},
  {'value': '949', 'Description': '5 Electricidad, gas y agua'},
  {'value': '950', 'Description': '6 Comercio, restaurantes y hoteles'},
  {'value': '951', 'Description': '7 Transporte, almacenaje y comunicaciones'},
  {'value': '952',
   'Description': '8 Servicios financieros, seguros, actividades inmobiliarias y de alquiler'},
  {'value': '953',
   'Description': '9 Servicios comunales, sociales y personales'},
  {'value': '954',
   'Description': 'Cargo por los servicios bancarios imputados'},
  {'value': '975', 'Description': 'Total'},
  {'value': '976',
   'Description': 'I   Productos alimenticios, bebidas y tabaco'},
  {'value': '977',
   'Description': 'II   Textiles, prendas de vestir e industria del cuero'},
  {'value': '978',
   'Description': 'III Industria de la madera y productos de madera'},
  {'value': '979',
   'Description': 'IV   Papel, productos de papel, imprentas y editoriales'},
  {'value': '980',
   'Description': 'V     Sustancias químicas, derivados del petróleo, productos de caucho y plástico'},
  {'value': '981',
   'Description': 'VI   Productos de minerales no metálicos, excepto derivados del petróleo y carbón'},
  {'value': '982', 'Description': 'VII Industrias metálicas básicas'},
  {'value': '983',
   'Description': 'VIII Productos metálicos, maquinaria y equipo'},
  {'value': '984', 'Description': 'IX   Otras industrias manufactureras'},
  {'value': '1005', 'Description': 'Total'},
  {'value': '1006',
   'Description': 'Impuestos a los productos netos de subsidios'},
  {'value': '1007', 'Description': 'Valor agregado bruto en valores básicos'},
  {'value': '1008', 'Description': '1 Agropecuario, silvicultura y pesca'},
  {'value': '1009', 'Description': '2 Minería'},
  {'value': '1010', 'Description': '3 Industria manufacturera'},
  {'value': '1011', 'Description': '4 Construcción'},
  {'value': '1012', 'Description': '5 Electricidad, gas y agua'},
  {'value': '1013', 'Description': '6 Comercio, restaurantes y hoteles'},
  {'value': '1014',
   'Description': '7 Transporte, almacenaje y comunicaciones'},
  {'value': '1015',
   'Description': '8 Servicios financieros, seguros, actividades inmobiliarias y de alquiler'},
  {'value': '1016',
   'Description': '9 Servicios comunales, sociales y personales'},
  {'value': '1017',
   'Description': 'Cargo por los servicios bancarios imputados'},
  {'value': '1018', 'Description': 'Total'},
  {'value': '1019',
   'Description': 'I   Productos alimenticios, bebidas y tabaco'},
  {'value': '1020',
   'Description': 'II   Textiles, prendas de vestir e industria del cuero'},
  {'value': '1021',
   'Description': 'III Industria de la madera y productos de madera'},
  {'value': '1022',
   'Description': 'IV   Papel, productos de papel, imprentas y editoriales'},
  {'value': '1023',
   'Description': 'V     Sustancias químicas, derivados del petróleo, productos de caucho y plástico'},
  {'value': '1024',
   'Description': 'VI   Productos de minerales no metálicos, excepto derivados del petróleo y carbón'},
  {'value': '1025', 'Description': 'VII Industrias metálicas básicas'},
  {'value': '1026',
   'Description': 'VIII Productos metálicos, maquinaria y equipo'},
  {'value': '1027', 'Description': 'IX   Otras industrias manufactureras'},
  {'value': '1028', 'Description': 'Total'},
  {'value': '1029',
   'Description': 'Impuestos a los productos netos de subsidios'},
  {'value': '1030', 'Description': 'Valor agregado bruto en valores básicos'},
  {'value': '1031', 'Description': '1 Agropecuario, silvicultura y pesca'},
  {'value': '1032', 'Description': '2 Minería'},
  {'value': '1033', 'Description': '3 Industria manufacturera'},
  {'value': '1034', 'Description': '4 Construcción'},
  {'value': '1035', 'Description': '5 Electricidad, gas y agua'},
  {'value': '1036', 'Description': '6 Comercio, restaurantes y hoteles'},
  {'value': '1037',
   'Description': '7 Transporte, almacenaje y comunicaciones'},
  {'value': '1038',
   'Description': '8 Servicios financieros, seguros, actividades inmobiliarias y de alquiler'},
  {'value': '1039',
   'Description': '9 Servicios comunales, sociales y personales'},
  {'value': '1062', 'Description': 'Total'},
  {'value': '1063',
   'Description': 'I   Productos alimenticios, bebidas y tabaco'},
  {'value': '1064',
   'Description': 'II   Textiles, prendas de vestir e industria del cuero'},
  {'value': '1065',
   'Description': 'III Industria de la madera y productos de madera'},
  {'value': '1066',
   'Description': 'IV   Papel, productos de papel, imprentas y editoriales'},
  {'value': '1067',
   'Description': 'V     Sustancias químicas, derivados del petróleo, productos de caucho y plástico'},
  {'value': '1068',
   'Description': 'VI   Productos de minerales no metálicos, excepto derivados del petróleo y carbón'},
  {'value': '1069', 'Description': 'VII Industrias metálicas básicas'},
  {'value': '1070',
   'Description': 'VIII Productos metálicos, maquinaria y equipo'},
  {'value': '1071', 'Description': 'IX   Otras industrias manufactureras'},
  {'value': '1092', 'Description': 'Total'},
  {'value': '1093', 'Description': 'Producto interno bruto'},
  {'value': '1094', 'Description': 'Importación de bienes y servicios'},
  {'value': '1095', 'Description': 'Total'},
  {'value': '1096', 'Description': 'Consumo privado'},
  {'value': '1097', 'Description': 'Consumo del gobierno general'},
  {'value': '1098', 'Description': 'Formación bruta de capital fijo'},
  {'value': '1099', 'Description': 'Variación de existencias'},
  {'value': '1100', 'Description': 'Exportación de bienes y servicios'},
  {'value': '1101', 'Description': 'Total'},
  {'value': '1102', 'Description': 'Bienes FOB'},
  {'value': '1103', 'Description': 'Bienes para maquila'},
  {'value': '1104', 'Description': 'Servicios'},
  {'value': '1105', 'Description': 'Total'},
  {'value': '1106', 'Description': 'Bienes para consumo intermedio'},
  {'value': '1107', 'Description': 'Bienes para consumo final'},
  {'value': '1108',
   'Description': 'Bienes para formación bruta de capital fijo'},
  {'value': '1109', 'Description': 'Bienes duraderos'},
  {'value': '1110', 'Description': 'Bienes no duraderos'},
  {'value': '1111', 'Description': 'Servicios'},
  {'value': '1112', 'Description': 'Subtotal de gastos en el mercado interno'},
  {'value': '1113', 'Description': 'Compras netas en el mercado exterior'},
  {'value': '1114', 'Description': 'Total'},
  {'value': '1115', 'Description': 'Total'},
  {'value': '1116', 'Description': 'Bienes duraderos'},
  {'value': '1117', 'Description': 'Bienes no duraderos y servicios'},
  {'value': '1118', 'Description': 'Total'},
  {'value': '1119', 'Description': 'Bienes duraderos'},
  {'value': '1120', 'Description': 'Bienes no duraderos y servicios'},
  {'value': '1121', 'Description': 'Total'},
  {'value': '1122', 'Description': 'Compra de bienes y servicios'},
  {'value': '1123', 'Description': 'Valor agregado bruto'},
  {'value': '1124', 'Description': 'Total formación bruta de capital fijo'},
  {'value': '1125', 'Description': 'Total'},
  {'value': '1126', 'Description': 'Construcción'},
  {'value': '1127', 'Description': 'Total'},
  {'value': '1128', 'Description': 'Equipo de transporte'},
  {'value': '1129', 'Description': 'Maquinaria, equipo y otros bienes'},
  {'value': '1130', 'Description': 'Total'},
  {'value': '1131', 'Description': 'Equipo de transporte'},
  {'value': '1132', 'Description': 'Maquinaria, equipo y otros bienes'},
  {'value': '1133', 'Description': 'Total'},
  {'value': '1134', 'Description': 'Construcción'},
  {'value': '1135', 'Description': 'Maquinaria y equipo'},
  {'value': '1136', 'Description': 'Total'},
  {'value': '1137', 'Description': 'Construcción'},
  {'value': '1138', 'Description': 'Maquinaria y equipo'},
  {'value': '1139', 'Description': 'Total'},
  {'value': '1140', 'Description': 'Construcción'},
  {'value': '1141', 'Description': 'Maquinaria y equipo'},
  {'value': '1142', 'Description': 'Total'},
  {'value': '1143', 'Description': 'Bienes maquilados'},
  {'value': '1144', 'Description': 'Plata y oro no monetario'},
  {'value': '1145', 'Description': 'Otros servicios'},
  {'value': '1146', 'Description': 'Total'},
  {'value': '1147', 'Description': 'Total'},
  {'value': '1148', 'Description': 'Agricultura, silvicultura y pesca'},
  {'value': '1149', 'Description': 'Minería con petróleo'},
  {'value': '1150', 'Description': 'Industria manufacturera'},
  {'value': '1151', 'Description': 'Petróleo crudo y gas natural'},
  {'value': '1152', 'Description': 'Total'},
  {'value': '1153', 'Description': 'Producto interno bruto'},
  {'value': '1154', 'Description': 'Importación de bienes y servicios'},
  {'value': '1155', 'Description': 'Total'},
  {'value': '1156', 'Description': 'Consumo privado'},
  {'value': '1157', 'Description': 'Consumo del gobierno general'},
  {'value': '1158', 'Description': 'Formación bruta de capital fijo'},
  {'value': '1159', 'Description': 'Variación de existencias'},
  {'value': '1160', 'Description': 'Exportación de bienes y servicios'},
  {'value': '1161', 'Description': 'Total'},
  {'value': '1162', 'Description': 'Bienes FOB'},
  {'value': '1163', 'Description': 'Bienes para maquila'},
  {'value': '1164', 'Description': 'Servicios'},
  {'value': '1165', 'Description': 'Total'},
  {'value': '1166', 'Description': 'Bienes para consumo intermedio'},
  {'value': '1167', 'Description': 'Bienes para consumo final'},
  {'value': '1168',
   'Description': 'Bienes para formación bruta de capital fijo'},
  {'value': '1169', 'Description': 'Bienes duraderos'},
  {'value': '1170', 'Description': 'Bienes no duraderos'},
  {'value': '1171', 'Description': 'Servicios'},
  {'value': '1172', 'Description': 'Subtotal de gastos en el mercado interno'},
  {'value': '1173', 'Description': 'Compras netas en el mercado exterior'},
  {'value': '1174', 'Description': 'Total'},
  {'value': '1175', 'Description': 'Total'},
  {'value': '1176', 'Description': 'Bienes duraderos'},
  {'value': '1177', 'Description': 'Bienes no duraderos y servicios'},
  {'value': '1178', 'Description': 'Total'},
  {'value': '1179', 'Description': 'Bienes duraderos'},
  {'value': '1180', 'Description': 'Bienes no duraderos y servicios'},
  {'value': '1181', 'Description': 'Total formación bruta de capital fijo'},
  {'value': '1182', 'Description': 'Total'},
  {'value': '1183', 'Description': 'Construcción'},
  {'value': '1184', 'Description': 'Total'},
  {'value': '1185', 'Description': 'Equipo de transporte'},
  {'value': '1186', 'Description': 'Maquinaria, equipo y otros bienes'},
  {'value': '1187', 'Description': 'Total'},
  {'value': '1188', 'Description': 'Equipo de transporte'},
  {'value': '1189', 'Description': 'Maquinaria, equipo y otros bienes'},
  {'value': '1190', 'Description': 'Total'},
  {'value': '1191', 'Description': 'Construcción'},
  {'value': '1192', 'Description': 'Maquinaria y equipo'},
  {'value': '1193', 'Description': 'Total'},
  {'value': '1194', 'Description': 'Construcción'},
  {'value': '1195', 'Description': 'Maquinaria y equipo'},
  {'value': '1196', 'Description': 'Total'},
  {'value': '1197', 'Description': 'Construcción'},
  {'value': '1198', 'Description': 'Maquinaria y equipo'},
  {'value': '1199', 'Description': 'Total'},
  {'value': '1200', 'Description': 'Bienes maquilados'},

In [19]:
[(x['value'], x['Description']) for x in json.loads(s)['CODE'] if x['value'][:3] == '628']

[('6280', 'Volumen'),
 ('6281', 'Valor'),
 ('6282', 'Volumen'),
 ('6283', 'Valor'),
 ('6284', 'Valor'),
 ('6285', 'Valor'),
 ('6286', 'Valor'),
 ('6287', 'Valor'),
 ('6288', 'Valor'),
 ('6289', 'Valor total de la clase'),
 ('62800', 'Total'),
 ('62801', 'De origen importado'),
 ('62802', 'De origen nacional'),
 ('62803', 'Total'),
 ('62804', 'Salarios'),
 ('62805', 'Sueldos'),
 ('62806', 'Superávit bruto de operación'),
 ('62807', 'Producción'),
 ('62808', 'Consumo intermedio'),
 ('62809', 'Valor agregado bruto'),
 ('62810', 'Total'),
 ('62811', 'Obreros'),
 ('62812', 'Empleados'),
 ('62813', 'Total'),
 ('62814', 'Obreros'),
 ('62815', 'Empleados'),
 ('62816', 'Índice de productividad'),
 ('62817', 'Producción'),
 ('62818', 'Total'),
 ('62819', 'De origen importado'),
 ('62820', 'De origen nacional'),
 ('62821', 'Total'),
 ('62822', 'Salarios'),
 ('62823', 'Sueldos'),
 ('62824', 'Superávit bruto de operación'),
 ('62825', 'Producción'),
 ('62826', 'Consumo intermedio'),
 ('62827', 'Valor agregado bruto'),
 ('62828', 'Total'),
 ('62829', 'Obreros'),
 ('62830', 'Empleados'),
 ('62831', 'Total'),
 ('62832', 'Obreros'),
 ('62833', 'Empleados'),
 ('62834', 'Índice de productividad'),
 ('62835', 'Producción'),
 ('62836', 'Total'),
 ('62837', 'De origen importado'),
 ('62838', 'De origen nacional'),
 ('62839', 'Total'),
 ('62840', 'Salarios'),
 ('62841', 'Sueldos'),
 ('62842', 'Superávit bruto de operación'),
 ('62843', 'Producción'),
 ('62844', 'Consumo intermedio'),
 ('62845', 'Valor agregado bruto'),
 ('62846', 'Total'),
 ('62847', 'Obreros'),
 ('62848', 'Empleados'),
 ('62849', 'Total'),
 ('62850', 'Obreros'),
 ('62851', 'Empleados'),
 ('62852', 'Índice de productividad'),
 ('62853', 'Producción'),
 ('62854', 'Total'),
 ('62855', 'De origen importado'),
 ('62856', 'De origen nacional'),
 ('62857', 'Total'),
 ('62858', 'Salarios'),
 ('62859', 'Sueldos'),
 ('62860', 'Superávit bruto de operación'),
 ('62861', 'Producción'),
 ('62862', 'Consumo intermedio'),
 ('62863', 'Valor agregado bruto'),
 ('62864', 'Total'),
 ('62865', 'Obreros'),
 ('62866', 'Empleados'),
 ('62867', 'Total'),
 ('62868', 'Obreros'),
 ('62869', 'Empleados'),
 ('62870', 'Índice de productividad'),
 ('62871', 'Producción'),
 ('62872', 'Total'),
 ('62873', 'De origen importado'),
 ('62874', 'De origen nacional'),
 ('62875', 'Total'),
 ('62876', 'Salarios'),
 ('62877', 'Sueldos'),
 ('62878', 'Superávit bruto de operación'),
 ('62879', 'Producción'),
 ('62880', 'Consumo intermedio'),
 ('62881', 'Valor agregado bruto'),
 ('62882', 'Total'),
 ('62883', 'Obreros'),
 ('62884', 'Empleados'),
 ('62885', 'Total'),
 ('62886', 'Obreros'),
 ('62887', 'Empleados'),
 ('62889', 'Ciudad Victoria'),
 ('62891', 'Reynosa'),
 ('62892', 'Tuxpam'),
 ('628000', '10.5.0 Educación no atribuíble a algún nivel'),
 ('628001', '267 Carrera corta'),
 ('628002', '268 Enseñanza adicional'),
 ('628003', '11 Restaurantes y hoteles'),
 ('628004', '11.1 Servicios de suministro de comidas'),
 ('628005', '11.1.1 Restaurantes, cafés y establecimientos similares'),
 ('628006', '269 Barbacoa o birria'),
 ('628007', '270 Carnitas'),
 ('628008', '271 Centro nocturno'),
 ('628009', '272 Loncherías, fondas, torterías y taquerías'),
 ('628010', '273 Otros alimentos cocinados'),
 ('628011', '274 Pizzas'),
 ('628012', '275 Pollos rostizados'),
 ('628013', '276 Restaurantes y similares'),
 ('628014', '11.2 Servicios de alojamiento'),
 ('628015', '11.2.0 Servicios de alojamiento'),
 ('628016', '277 Hoteles'),
 ('628017', '12 Bienes y servicios diversos'),
 ('628018', '12.1 Cuidado personal'),
 ('628019', '12.1.1 Salones de peluquería de cuidado personal'),
 ('628020', '278 Corte de cabello'),
 ('628021', '279 Sala de belleza y masajes'),
 ('628022', '12.1.2 Aparatos eléctricos para el cuidado personal'),
 ('628023', '280 Aparatos eléctricos para el cuidado personal'),
 ('628024', '281 Navajas y máquinas de afeitar'),
 ('628025',
  '12.1.3 Otros aparatos, artículos y productos para el cuidado personal'),
 ('628026', '282 Artículos de maquillaje'),
 ('628027', '283 Crema y productos para higiene dental'),
 ('628028', '284 Cremas para la piel'),
 ('628029', '285 Desodorantes personales'),
 ('628030', '286 Jabón de tocador'),
 ('628031', '287 Lociones y perfumes'),
 ('628032', '288 Otros artículos de tocador'),
 ('628033', '289 Pañales'),
 ('628034', '290 Papel higiénico y pañuelos desechables'),
 ('628035', '291 Productos para el cabello'),
 ('628036', '292 Toallas sanitarias'),
 ('628037', '12.3 Efectos personales'),
 ('628038', '12.3.1 Joyería, relojes de pared y relojes de pulsera'),
 ('628039', '293 Relojes, joyas y bisutería'),
 ('628040', '12.3.2 Otros efectos personales'),
 ('628041', '294 Bolsas, maletas y cinturones'),
 ('628042', '12.4 Protección social'),
 ('628043', '12.4.1 Protección social'),
 ('628044', '295 Guarderías y estancias infantiles'),
 ('628045', '12.5 Seguros'),
 ('628046', '12.5.4 Seguros'),
 ('628047', '296 Seguro de automóvil'),
 ('628048', '12.7 Otros servicios'),
 ('628049', '12.7.0 Otros servicios'),
 ('628050', '297 Expedición de documentos del sector público'),
 ('628051', '298 Servicios funerarios'),
 ('628052', '299 Servicios profesionales'),
 ('628053', '20 Todos los artículos excluyendo comida y energía'),
 ('628054', '21 Energía'),
 ('628055', '22 Servicios'),
 ('628056', '23 Bienes'),
 ('628057', '24 Servicios menos viviendas'),
 ('628058', '25 Vivienda'),
 ('628059', 'Total'),
 ('628060', '01 Alimentos y bebidas no alcohólicas'),
 ('628061', '02 Bebidas alcohólicas y tabaco'),
 ('628062', '03 Prendas de vestir y calzado'),
 ('628063', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628064', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628065', '06 Salud'),
 ('628066', '07 Transporte'),
 ('628067', '08 Comunicaciones'),
 ('628068', '09 Recreación y cultura'),
 ('628069', '10 Educación'),
 ('628070', '11 Restaurantes y hoteles'),
 ('628071', '12 Bienes y servicios diversos'),
 ('628072', 'Índice general (Hasta un salario mínimo)'),
 ('628073', '01 Alimentos y bebidas no alcohólicas'),
 ('628074', '02 Bebidas alcohólicas y tabaco'),
 ('628075', '03 Prendas de vestir y calzado'),
 ('628076', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628077', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628078', '06 Salud'),
 ('628079', '07 Transporte'),
 ('628080', '08 Comunicaciones'),
 ('628081', '09 Recreación y cultura'),
 ('628082', '10 Educación'),
 ('628083', '11 Restaurantes y hoteles'),
 ('628084', '12 Bienes y servicios diversos'),
 ('628085', 'Índice general (Entre 1 y 3 salarios mínimos)'),
 ('628086', '01 Alimentos y bebidas no alcohólicas'),
 ('628087', '02 Bebidas alcohólicas y tabaco'),
 ('628088', '03 Prendas de vestir y calzado'),
 ('628089', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628090', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628091', '06 Salud'),
 ('628092', '07 Transporte'),
 ('628093', '08 Comunicaciones'),
 ('628094', '09 Recreación y cultura'),
 ('628095', '10 Educación'),
 ('628096', '11 Restaurantes y hoteles'),
 ('628097', '12 Bienes y servicios diversos'),
 ('628098', 'Índice general (Entre 3 y 6 salarios mínimos)'),
 ('628099', '01 Alimentos y bebidas no alcohólicas'),
 ('628100', '02 Bebidas alcohólicas y tabaco'),
 ('628101', '03 Prendas de vestir y calzado'),
 ('628102', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628103', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628104', '06 Salud'),
 ('628105', '07 Transporte'),
 ('628106', '08 Comunicaciones'),
 ('628107', '09 Recreación y cultura'),
 ('628108', '10 Educación'),
 ('628109', '11 Restaurantes y hoteles'),
 ('628110', '12 Bienes y servicios diversos'),
 ('628111', 'Índice general (Superior a 6 salarios mínimos)'),
 ('628112', '01 Alimentos y bebidas no alcohólicas'),
 ('628113', '02 Bebidas alcohólicas y tabaco'),
 ('628114', '03 Prendas de vestir y calzado'),
 ('628115', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628116', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628117', '06 Salud'),
 ('628118', '07 Transporte'),
 ('628119', '08 Comunicaciones'),
 ('628120', '09 Recreación y cultura'),
 ('628121', '10 Educación'),
 ('628122', '11 Restaurantes y hoteles'),
 ('628123', '12 Bienes y servicios diversos'),
 ('628124', 'Precios al Consumidor (INPC)'),
 ('628125', 'Subyacente'),
 ('628126', 'Mercancías'),
 ('628127', 'Alimentos, bebidas y tabaco'),
 ('628128', 'Mercancías no alimenticias'),
 ('628129', 'Servicios'),
 ('628130', 'Vivienda'),
 ('628131', 'Educación (colegiaturas)'),
 ('628132', 'Otros servicios'),
 ('628133', 'No Subyacente (nueva definición)'),
 ('628134', 'Agropecuarios'),
 ('628135', 'Frutas y verduras'),
 ('628136', 'Pecuarios'),
 ('628137', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628138', 'Energéticos'),
 ('628139', 'Tarifas autorizadas por el gobierno'),
 ('628140', 'INPC'),
 ('628141', '01 Alimentos y bebidas no alcohólicas'),
 ('628142', '02 Bebidas alcohólicas y tabaco'),
 ('628143', '03 Prendas de vestir y calzado'),
 ('628144', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628145', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628146', '06 Salud'),
 ('628147', '07 Transporte'),
 ('628148', '08 Comunicaciones'),
 ('628149', '09 Recreación y cultura'),
 ('628150', '10 Educación'),
 ('628151', '11 Restaurantes y hoteles'),
 ('628152', '12 Bienes y servicios diversos'),
 ('628153', '20 Todos los artículos excluyendo comida y energía'),
 ('628154', '21 Energía'),
 ('628155', '22 Servicios'),
 ('628156', '23 Bienes'),
 ('628157', '24 Servicios menos viviendas'),
 ('628158', '25 Vivienda'),
 ('628159', 'Precios al Consumidor (INPC)'),
 ('628160', 'Subyacente'),
 ('628161', 'Mercancías'),
 ('628162', 'Alimentos, bebidas y tabaco'),
 ('628163', 'Mercancías no alimenticias'),
 ('628164', 'Servicios'),
 ('628165', 'Vivienda'),
 ('628166', 'Educación (colegiaturas)'),
 ('628167', 'Otros servicios'),
 ('628168', 'No Subyacente (nueva definición)'),
 ('628169', 'Agropecuarios'),
 ('628170', 'Frutas y verduras'),
 ('628171', 'Pecuarios'),
 ('628172', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628173', 'Energéticos'),
 ('628174', 'Tarifas autorizadas por el gobierno'),
 ('628175', 'INPC'),
 ('628176', '01 Alimentos y bebidas no alcohólicas'),
 ('628177', '02 Bebidas alcohólicas y tabaco'),
 ('628178', '03 Prendas de vestir y calzado'),
 ('628179', '04 Vivienda, agua, electricidad, gas y otros combustibles'),
 ('628180', '05 Muebles, artículos para el hogar y para su conservación'),
 ('628181', '06 Salud'),
 ('628182', '07 Transporte'),
 ('628183', '08 Comunicaciones'),
 ('628184', '09 Recreación y cultura'),
 ('628185', '10 Educación'),
 ('628186', '11 Restaurantes y hoteles'),
 ('628187', '12 Bienes y servicios diversos'),
 ('628188', '20 Todos los artículos excluyendo comida y energía'),
 ('628189', '21 Energía'),
 ('628190', '22 Servicios'),
 ('628191', '23 Bienes'),
 ('628192', '24 Servicios menos viviendas'),
 ('628193', '25 Vivienda'),
 ('628194', 'Índice general'),
 ('628195', 'total'),
 ('628196', 'Mercancías'),
 ('628197', 'Servicios'),
 ('628198', 'total'),
 ('628199', 'Agropecuarios'),
 ('628200', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628201', 'Índice general'),
 ('628202', 'total'),
 ('628203', 'Mercancías'),
 ('628204', 'Servicios'),
 ('628205', 'total'),
 ('628206', 'Agropecuarios'),
 ('628207', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628208', 'Índice general'),
 ('628209', 'total'),
 ('628210', 'Mercancías'),
 ('628211', 'Servicios'),
 ('628212', 'total'),
 ('628213', 'Agropecuarios'),
 ('628214', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628215', 'Índice general'),
 ('628216', 'total'),
 ('628217', 'Mercancías'),
 ('628218', 'Servicios'),
 ('628219', 'total'),
 ('628220', 'Agropecuarios'),
 ('628221', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628222', 'Índice general'),
 ('628223', 'total'),
 ('628224', 'Mercancías'),
 ('628225', 'Servicios'),
 ('628226', 'total'),
 ('628227', 'Agropecuarios'),
 ('628228', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628229', 'Índice general'),
 ('628230', 'total'),
 ('628231', 'Mercancías'),
 ('628232', 'Servicios'),
 ('628233', 'total'),
 ('628234', 'Agropecuarios'),
 ('628235', 'Energéticos y tarifas autorizadas por el gobierno'),
 ('628236', '26 Mantenimiento y reparación de la vivienda'),
 ('628237', '26 Mantenimiento y reparación de la vivienda'),
 ('628238', '26 Mantenimiento y reparación de la vivienda'),
 ('628239', '26 Mantenimiento y reparación de la vivienda'),
 ('628240', 'Índice'),
 ('628241', 'Variación anual'),
 ('628242', 'Índice'),
 ('628243', 'Variación mensual'),
 ('628244', 'Variación anual'),
 ('628245', 'Índice'),
 ('628246', 'Variación mensual'),
 ('628247', 'Producto Interno Bruto, a precios de mercado'),
 ('628248', 'Actividades primarias'),
 ('628249', 'Actividades secundarias'),
 ('628250', 'Actividades terciarias'),
 ('628251', 'Producto Interno Bruto, a precios de mercado'),
 ('628252', 'Actividades primarias'),
 ('628253', 'Actividades secundarias'),
 ('628254', 'Actividades terciarias'),
 ('628255', 'Producto Interno Bruto, a precios de mercado'),
 ('628256', 'Actividades primarias'),
 ('628257', 'Actividades secundarias'),
 ('628258', 'Actividades terciarias'),
 ('628259', 'Todos los artículos excluyendo comida y energía'),
 ('628260', 'Energía'),
 ('628261', 'Servicios'),
 ('628262', 'Bienes'),
 ('628263', 'Servicios menos viviendas'),
 ('628264', 'Vivienda'),
 ('628265', 'Renta de vivienda'),
 ('628266', 'Vivienda propia'),
 ('628267', 'Agua y otros servicios referentes a la vivienda'),
 ('628268', 'Electricidad, gas y otros combustibles'),
 ('628269', 'Combustibles y lubricantes para equipo de transporte personal'),
 ('628270', 'Valores absolutos'),
 ('628271', 'Variación anual'),
 ('628272', 'Valores absolutos'),
 ('628273', 'Variación trimestral'),
 ('628274', 'Variación anual'),
 ('628275', 'Valores absolutos'),
 ('628276', 'Variación trimestral'),
 ('628277', 'Valores absolutos'),
 ('628278', 'Variación anual'),
 ('628279', 'Valores absolutos'),
 ('628280', 'Variación trimestral'),
 ('628281', 'Variación anual'),
 ('628282', 'Valores absolutos'),
 ('628283', 'Variación trimestral'),
 ('628284', 'Valores absolutos'),
 ('628285', 'Variación anual'),
 ('628286', 'Valores absolutos'),
 ('628287', 'Variación trimestral'),
 ('628288', 'Variación anual'),
 ('628289', 'Valores absolutos'),
 ('628290', 'Variación trimestral'),
 ('628291', 'Valores absolutos'),
 ('628292', 'Variación anual'),
 ('628293', 'Valores absolutos'),
 ('628294', 'Variación trimestral'),
 ('628295', 'Variación anual'),
 ('628296', 'Valores absolutos'),
 ('628297', 'Variación trimestral'),
 ('628298', 'Serie original corregida por efectos del calendario'),
 ('628300', 'Serie desestacionalizada'),
 ('628303', 'Tendencia-ciclo'),
 ('628304', 'Valores absolutos'),
 ('628305', 'Variación anual'),
 ('628306', 'Valores absolutos'),
 ('628307', 'Variación trimestral'),
 ('628308', 'Variación anual'),
 ('628309', 'Valores absolutos'),
 ('628310', 'Variación trimestral'),
 ('628311', 'Valores absolutos'),
 ('628312', 'Variación anual'),
 ('628313', 'Valores absolutos'),
 ('628314', 'Variación trimestral'),
 ('628315', 'Variación anual'),
 ('628316', 'Valores absolutos'),
 ('628317', 'Variación trimestral'),
 ('628318', 'Valores absolutos'),
 ('628319', 'Variación anual'),
 ('628320', 'Valores absolutos'),
 ('628321', 'Variación trimestral'),
 ('628322', 'Variación anual'),
 ('628323', 'Valores absolutos'),
 ('628324', 'Variación trimestral'),
 ('628325', 'Serie original corregida por efectos del calendario'),
 ('628326', 'Serie desestacionalizada'),
 ('628327', 'Tendencia-ciclo'),
 ('628328',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628329', 'Variación anual (Puntos porcentuales)'),
 ('628330',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628331', 'Variación trimestral (Puntos porcentuales)'),
 ('628332', 'Variación anual (Puntos porcentuales)'),
 ('628333',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628334', 'Variación trimestral (Puntos porcentuales)'),
 ('628335',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628336', 'Variación anual (Puntos porcentuales)'),
 ('628337',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628338', 'Variación trimestral (Puntos porcentuales)'),
 ('628339', 'Variación anual (Puntos porcentuales)'),
 ('628340',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628341', 'Variación trimestral (Puntos porcentuales)'),
 ('628342',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628343', 'Variación anual (Puntos porcentuales)'),
 ('628344',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628345', 'Variación trimestral (Puntos porcentuales)'),
 ('628346', 'Variación anual (Puntos porcentuales)'),
 ('628347',
  'Participación porcentual (Porcentaje del producto interno bruto)'),
 ('628348', 'Variación trimestral (Puntos porcentuales)')]

In [26]:
p = {'type': 'json'}
tic = 'mxn_cpi_mom'
id = ticker_map[tic]['id'] 
cat = catalogue[5]
source = sources[1]
url = ('http://en.www.inegi.org.mx/app/api/indicadores/desarrolladores/jsonxml/INDICATOR/'
            + id
            + '/en/0700/false/' 
            + source 
            + '/2.0/' 
            + API_KEYS['INEGI_API_KEY'])

In [27]:
s = requests.get(url, p).text

In [28]:
json.loads(s)

{'Header': {'Name': 'Datos compactos BIE',
  'Email': 'atencion.usuarios@inegi.org.mx'},
 'Series': [{'INDICADOR': '628201',
   'FREQ': '8',
   'TOPIC': '100005000015002000800035',
   'UNIT': '60',
   'UNIT_MULT': None,
   'NOTE': '',
   'SOURCE': '127',
   'LASTUPDATE': '09/03/2023 01:23:22 p. m.',
   'STATUS': None,
   'OBSERVATIONS': [{'TIME_PERIOD': '2023/02',
     'OBS_VALUE': '0.56',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2023/01',
     'OBS_VALUE': '0.68',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/12',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/11',
     'OBS_VALUE': '0.58',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/10',
     'OBS_VALUE': '0.57',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/09',
     'OBS_VALUE': '0.62',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/08',
     'OBS_VALUE': '0.7',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/07',
     'OBS_VALUE': '0.74',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/06',
     'OBS_VALUE': '0.84',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/05',
     'OBS_VALUE': '0.18',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/04',
     'OBS_VALUE': '0.54',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/03',
     'OBS_VALUE': '0.99',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/02',
     'OBS_VALUE': '0.83',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2022/01',
     'OBS_VALUE': '0.59',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/12',
     'OBS_VALUE': '0.36',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/11',
     'OBS_VALUE': '1.14',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/10',
     'OBS_VALUE': '0.84',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/09',
     'OBS_VALUE': '0.62',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/08',
     'OBS_VALUE': '0.19',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/07',
     'OBS_VALUE': '0.59',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/06',
     'OBS_VALUE': '0.53',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/05',
     'OBS_VALUE': '0.2',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/04',
     'OBS_VALUE': '0.33',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/03',
     'OBS_VALUE': '0.83',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/02',
     'OBS_VALUE': '0.63',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2021/01',
     'OBS_VALUE': '0.86',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/12',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/11',
     'OBS_VALUE': '0.08',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/10',
     'OBS_VALUE': '0.61',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/09',
     'OBS_VALUE': '0.23',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/08',
     'OBS_VALUE': '0.39',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/07',
     'OBS_VALUE': '0.66',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/06',
     'OBS_VALUE': '0.55',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/05',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/04',
     'OBS_VALUE': '-1.01',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/03',
     'OBS_VALUE': '-0.05',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/02',
     'OBS_VALUE': '0.42',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2020/01',
     'OBS_VALUE': '0.48',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/12',
     'OBS_VALUE': '0.56',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/11',
     'OBS_VALUE': '0.81',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/10',
     'OBS_VALUE': '0.54',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/09',
     'OBS_VALUE': '0.26',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/08',
     'OBS_VALUE': '-0.02',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/07',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/06',
     'OBS_VALUE': '0.06',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/05',
     'OBS_VALUE': '-0.29',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/04',
     'OBS_VALUE': '0.05',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/03',
     'OBS_VALUE': '0.39',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/02',
     'OBS_VALUE': '-0.03',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2019/01',
     'OBS_VALUE': '0.09',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/12',
     'OBS_VALUE': '0.7',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/11',
     'OBS_VALUE': '0.85',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/10',
     'OBS_VALUE': '0.52',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/09',
     'OBS_VALUE': '0.42',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/08',
     'OBS_VALUE': '0.58',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/07',
     'OBS_VALUE': '0.54',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/06',
     'OBS_VALUE': '0.39',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/05',
     'OBS_VALUE': '-0.16',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/04',
     'OBS_VALUE': '-0.34',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/03',
     'OBS_VALUE': '0.32',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/02',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2018/01',
     'OBS_VALUE': '0.53',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/12',
     'OBS_VALUE': '0.59',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/11',
     'OBS_VALUE': '1.03',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/10',
     'OBS_VALUE': '0.63',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/09',
     'OBS_VALUE': '0.31',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/08',
     'OBS_VALUE': '0.49',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/07',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/06',
     'OBS_VALUE': '0.25',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/05',
     'OBS_VALUE': '-0.12',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/04',
     'OBS_VALUE': '0.12',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/03',
     'OBS_VALUE': '0.61',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/02',
     'OBS_VALUE': '0.58',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2017/01',
     'OBS_VALUE': '1.7',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/12',
     'OBS_VALUE': '0.46',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/11',
     'OBS_VALUE': '0.78',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/10',
     'OBS_VALUE': '0.61',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/09',
     'OBS_VALUE': '0.61',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/08',
     'OBS_VALUE': '0.28',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/07',
     'OBS_VALUE': '0.26',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/06',
     'OBS_VALUE': '0.11',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/05',
     'OBS_VALUE': '-0.45',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/04',
     'OBS_VALUE': '-0.32',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/03',
     'OBS_VALUE': '0.15',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/02',
     'OBS_VALUE': '0.44',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2016/01',
     'OBS_VALUE': '0.38',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/12',
     'OBS_VALUE': '0.41',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/11',
     'OBS_VALUE': '0.55',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/10',
     'OBS_VALUE': '0.51',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/09',
     'OBS_VALUE': '0.37',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/08',
     'OBS_VALUE': '0.21',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/07',
     'OBS_VALUE': '0.15',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/06',
     'OBS_VALUE': '0.17',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/05',
     'OBS_VALUE': '-0.5',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/04',
     'OBS_VALUE': '-0.26',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/03',
     'OBS_VALUE': '0.41',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/02',
     'OBS_VALUE': '0.19',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2015/01',
     'OBS_VALUE': '-0.09',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/12',
     'OBS_VALUE': '0.49',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/11',
     'OBS_VALUE': '0.81',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/10',
     'OBS_VALUE': '0.55',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/09',
     'OBS_VALUE': '0.44',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/08',
     'OBS_VALUE': '0.36',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/07',
     'OBS_VALUE': '0.28',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/06',
     'OBS_VALUE': '0.17',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/05',
     'OBS_VALUE': '-0.32',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/04',
     'OBS_VALUE': '-0.19',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/03',
     'OBS_VALUE': '0.27',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/02',
     'OBS_VALUE': '0.25',
     'OBS_EXCEPTION': '',
     'OBS_STATUS': '',
     'OBS_SOURCE': '127',
     'OBS_NOTE': None,
     'COBER_GEO': '00'},
    {'TIME_PERIOD': '2014/01',

In [1]:
from macroData.macrodata.modules import Philly
from datetime import date

start = date(1980, 1, 1)
end = date(2022, 11, 1)

tickers = ['us_cur_activity', 'us_cur_new_orders']

b = Philly(tickers, start, end, 'M').update()

Retrieving data from Philly Fed...
Real start : 1980-01-01, format <class 'datetime.date'>
Real end : 2022-11-01

In [2]:
b

            us_cur_activity  us_cur_new_orders
DATE
1980-01-31            -18.4              -20.1
1980-02-29            -20.9              -22.9
1980-03-31            -19.5              -29.1
1980-04-30            -37.1              -32.4
1980-05-30            -53.4              -53.5
...                     ...                ...
2022-06-30             -3.3              -12.4
2022-07-29            -12.3              -24.8
2022-08-31              6.2               -5.1
2022-09-30             -9.9              -17.6
2022-10-31             -8.7              -15.9

[514 rows x 2 columns]

In [8]:
import requests
import io
import pandas as pd
from datetime import datetime as dt
url = 'https://www.philadelphiafed.org/-/media/frbp/assets/surveys-and-data/mbos/historical-data/diffusion-indexes/bos_dif.csv?la=en&hash=433F3C508D5269FD08053D9CCB63FBD7'
_s = requests.get(url).content
_df = pd.read_csv(io.StringIO(_s.decode('utf-8')), index_col=0)

In [9]:
dt.strptime(_df.index[0], '%b-%y').date()

datetime.date(2068, 5, 1)

In [1]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['us_cur_activity', 'us_cur_new_orders']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from Philly Fed...

In [2]:
d.data

            us_cur_activity  us_cur_new_orders
1970-01-31            -13.1               -5.2
1970-02-28            -18.1                5.4
1970-03-31            -31.2                0.9
1970-04-30            -16.9                7.5
1970-05-31            -21.5               -1.3
...                     ...                ...
2022-06-30             -3.3              -12.4
2022-07-31            -12.3              -24.8
2022-08-31              6.2               -5.1
2022-09-30             -9.9              -17.6
2022-10-31             -8.7              -15.9

[634 rows x 2 columns]

In [3]:
d.desc()

Total non NA data : 634
From 1970-01-31 to 2022-10-31
Theorical number of months : 634

                          last_date last_value
philly us_cur_activity   2022-10-31       -8.7
       us_cur_new_orders 2022-10-31      -15.9

In [1]:
from macroData.macrodata.can import Client as can_Client
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['can_2y_rate', 'can_5y_rate']

b = can_Client(tickers, start, end, 'M')

Retrieving data from Canada Central Bank...

In [2]:
b.data

            can_2y_rate  can_5y_rate
2001-01-31         4.88         5.14
2001-02-28         4.81         5.09
2001-03-31         4.76         5.08
2001-04-30         4.88         5.37
2001-05-31         4.93         5.52
...                 ...          ...
2022-08-31         3.64         3.34
2022-09-30         3.79         3.32
2022-10-31         3.92         3.43
2022-11-30         3.89         3.18
2022-12-31         3.79         3.05

[264 rows x 2 columns]

In [6]:
b.data.index = [str(x.year) + str(x.month) for x in b.data.index]

In [8]:
b.data.index.name = 'dates'

In [11]:
b.data.drop_duplicates(subset='dates')

KeyError: Index(['dates'], dtype='object')

In [5]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['can_2y_rate', 'can_5y_rate']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from Canada Central Bank...

In [6]:
d.data

            can_2y_rate  can_5y_rate
1970-01-31          NaN          NaN
1970-02-28          NaN          NaN
1970-03-31          NaN          NaN
1970-04-30          NaN          NaN
1970-05-31          NaN          NaN
...                 ...          ...
2022-08-31         3.64         3.34
2022-09-30         3.79         3.32
2022-10-31         3.92         3.43
2022-11-30         3.89         3.18
2022-12-31         3.79         3.05

[636 rows x 2 columns]

In [4]:
from macroData.macrodata.modules import Yahoo
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['CORP', 'IXP']

b = Yahoo(tickers, start, end, 'M').update()

Retrieving data from Yahoo Finance...
[*********************100%***********************]  2 of 2 completed

In [5]:
b

                 CORP        IXP
2001-12-31        NaN  25.365345
2002-01-31        NaN  22.676395
2002-02-28        NaN  21.777594
2002-03-31        NaN  22.028080
2002-04-30        NaN  19.591970
...               ...        ...
2022-06-30  94.565338  60.643444
2022-07-31  97.902382  61.869999
2022-08-31  94.508781  59.619999
2022-09-30  90.161415  52.450001
2022-10-31  89.188301  51.930000

[251 rows x 2 columns]

In [1]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['corp', 'IXP']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from Yahoo Finance...
[*********************100%***********************]  2 of 2 completed

In [2]:
d.data

                 corp        IXP
1970-01-31        NaN        NaN
1970-02-28        NaN        NaN
1970-03-31        NaN        NaN
1970-04-30        NaN        NaN
1970-05-31        NaN        NaN
...               ...        ...
2022-06-30  94.565346  60.643444
2022-07-31  97.902374  61.869999
2022-08-31  94.508781  59.619999
2022-09-30  90.161423  52.450001
2022-10-31  89.188301  51.930000

[634 rows x 2 columns]

In [1]:
from macroData.macrodata.modules import Manual
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

tickers = ['us_ism_manufacturing']
# 'us_ism_new_orders'

b = Manual(tickers, start, end, 'M').update()

Retrieving data from Manual csv File...

In [2]:
b

            us_ism_manufacturing
1970-01-30                   NaN
1970-02-28                   NaN
1970-03-31                   NaN
1970-04-30                   NaN
1970-05-31                   NaN
...                          ...
2022-06-30                  53.0
2022-07-31                  52.8
2022-08-31                  52.8
2022-09-30                  50.9
2022-10-31                  50.2

[634 rows x 1 columns]

In [1]:
import json
import macroData.macrodata as md
from datetime import date

start = date(1970, 1, 1)
end = date(2022, 11, 1)

sec = json.load(open('macroData/macrodata/data_specs.json'))
selections = ['us_ism_manufacturing', 'jpy_cpi']
sel_sec = {x:sec[x] for x in selections}

d = md.Database(sel_sec, start, end, 'M')

Retrieving data from Manual csv File...

In [2]:
d.data

            us_ism_manufacturing  jpy_cpi
1970-01-30                   NaN     30.3
1970-01-31                   NaN      NaN
1970-02-28                   NaN     30.3
1970-03-31                   NaN     30.6
1970-04-30                   NaN     30.9
...                          ...      ...
2022-06-30                  53.0    101.8
2022-07-31                  52.8    102.3
2022-08-31                  52.8    102.7
2022-09-30                  50.9    103.1
2022-10-31                  50.2    103.7

[635 rows x 2 columns]